srcs-y += ocb_decrypt.c
srcs-y += ocb_decrypt_verify_memory.c
srcs-y += ocb_done_decrypt.c
srcs-y += ocb_done_encrypt.c
srcs-y += ocb_encrypt_authenticate_memory.c
srcs-y += ocb_encrypt.c
srcs-y += ocb_init.c
srcs-y += ocb_ntz.c
srcs-y += ocb_shift_xor.c
srcs-y += s_ocb_done.c
# srcs-y += ocb_test.c
