// SPDX-License-Identifier: BSD-2-Clause
/*
 * i.MX IOMUXC pin controller (i.MX6/7/8M), DT binding "fsl,pins":
 * <mux_reg conf_reg input_reg mux_val input_val pad_config> per pin, as
 * generated by the Linux <soc>-pinfunc.h macros.
 */
#include <drivers/pinctrl.h>
#include <io.h>
#include <kernel/dt.h>
#include <kernel/dt_driver.h>
#include <libfdt.h>
#include <malloc.h>
#include <trace.h>
#include <util.h>

#define FSL_PIN_CELLS		6

#define IMX_PAD_NO_PAD_CTL	BIT32(31)	/* leave pad config untouched */
#define IMX_PAD_SION		BIT32(30)	/* software input on */
#define IOMUXC_MUX_SION		BIT32(4)

struct imx_iomuxc {
	vaddr_t base;
	bool zero_offset_valid;
};

struct imx_pin {
	uint32_t mux_reg;
	uint32_t conf_reg;
	uint32_t input_reg;
	uint32_t mux_val;
	uint32_t input_val;
	uint32_t config;
};

struct imx_pin_group {
	struct imx_iomuxc *iomuxc;
	size_t count;
	struct imx_pin pins[];
};

static bool reg_valid(struct imx_iomuxc *iomuxc, uint32_t reg)
{
	return reg || iomuxc->zero_offset_valid;
}

static TEE_Result imx_pinctrl_conf_apply(struct pinconf *conf)
{
	struct imx_pin_group *grp = conf->priv;
	struct imx_iomuxc *iomuxc = grp->iomuxc;
	struct imx_pin *pin = NULL;
	uint32_t mux = 0;
	size_t n = 0;

	for (n = 0; n < grp->count; n++) {
		pin = grp->pins + n;

		if (reg_valid(iomuxc, pin->mux_reg)) {
			mux = pin->mux_val;
			if (pin->config & IMX_PAD_SION)
				mux |= IOMUXC_MUX_SION;
			io_write32(iomuxc->base + pin->mux_reg, mux);
		}

		/* Input select registers are never at offset 0 */
		if (pin->input_reg)
			io_write32(iomuxc->base + pin->input_reg,
				   pin->input_val);

		if (!(pin->config & IMX_PAD_NO_PAD_CTL) &&
		    reg_valid(iomuxc, pin->conf_reg))
			io_write32(iomuxc->base + pin->conf_reg,
				   pin->config & ~IMX_PAD_SION);
	}

	return TEE_SUCCESS;
}

static void imx_pinctrl_conf_free(struct pinconf *conf)
{
	free(conf);
}

static const struct pinctrl_ops imx_pinctrl_ops = {
	.conf_apply = imx_pinctrl_conf_apply,
	.conf_free = imx_pinctrl_conf_free,
};

static TEE_Result imx_pinctrl_dt_get(struct dt_pargs *pargs, void *data,
				     struct pinconf **out_pinconf)
{
	struct imx_pin_group *grp = NULL;
	struct pinconf *pinconf = NULL;
	const fdt32_t *cells = NULL;
	struct imx_pin *pin = NULL;
	size_t count = 0;
	size_t n = 0;
	int len = 0;

	cells = fdt_getprop(pargs->fdt, pargs->phandle_node, "fsl,pins", &len);
	if (!cells || len <= 0 ||
	    len % (FSL_PIN_CELLS * sizeof(uint32_t))) {
		EMSG("Invalid fsl,pins in node %d", pargs->phandle_node);
		return TEE_ERROR_BAD_FORMAT;
	}
	count = len / (FSL_PIN_CELLS * sizeof(uint32_t));

	pinconf = calloc(1, sizeof(*pinconf) + sizeof(*grp) +
			 count * sizeof(*pin));
	if (!pinconf)
		return TEE_ERROR_OUT_OF_MEMORY;

	grp = (struct imx_pin_group *)(pinconf + 1);
	grp->iomuxc = data;
	grp->count = count;

	for (n = 0; n < count; n++, cells += FSL_PIN_CELLS) {
		pin = grp->pins + n;
		pin->mux_reg = fdt32_to_cpu(cells[0]);
		pin->conf_reg = fdt32_to_cpu(cells[1]);
		pin->input_reg = fdt32_to_cpu(cells[2]);
		pin->mux_val = fdt32_to_cpu(cells[3]);
		pin->input_val = fdt32_to_cpu(cells[4]);
		pin->config = fdt32_to_cpu(cells[5]);
	}

	pinconf->ops = &imx_pinctrl_ops;
	pinconf->priv = grp;
	*out_pinconf = pinconf;

	return TEE_SUCCESS;
}

static TEE_Result imx_pinctrl_probe(const void *fdt, int node,
				    const void *compat_data)
{
	struct imx_iomuxc *iomuxc = NULL;
	TEE_Result res = TEE_ERROR_GENERIC;
	size_t size = 0;

	if (!(fdt_get_status(fdt, node) & DT_STATUS_OK_SEC))
		return TEE_SUCCESS;

	iomuxc = calloc(1, sizeof(*iomuxc));
	if (!iomuxc)
		return TEE_ERROR_OUT_OF_MEMORY;

	if (dt_map_dev(fdt, node, &iomuxc->base, &size, DT_MAP_AUTO) < 0) {
		res = TEE_ERROR_GENERIC;
		goto err;
	}
	iomuxc->zero_offset_valid = compat_data;

	res = pinctrl_register_provider(fdt, node, imx_pinctrl_dt_get, iomuxc);
	if (res)
		goto err;

	return TEE_SUCCESS;
err:
	free(iomuxc);

	return res;
}

/* Non-NULL compat data: register offset 0 is a valid pad register */
static const uint8_t zero_offset_valid;

static const struct dt_device_match imx_pinctrl_match_table[] = {
	{ .compatible = "fsl,imx6q-iomuxc" },
	{ .compatible = "fsl,imx6dl-iomuxc" },
	{ .compatible = "fsl,imx6sx-iomuxc" },
	{ .compatible = "fsl,imx6ul-iomuxc" },
	{ .compatible = "fsl,imx6ull-iomuxc-snvs",
	  .compat_data = &zero_offset_valid },
	{ .compatible = "fsl,imx7d-iomuxc" },
	{ .compatible = "fsl,imx7d-iomuxc-lpsr",
	  .compat_data = &zero_offset_valid },
	{ .compatible = "fsl,imx8mm-iomuxc" },
	{ .compatible = "fsl,imx8mn-iomuxc" },
	{ .compatible = "fsl,imx8mp-iomuxc" },
	{ .compatible = "fsl,imx8mq-iomuxc" },
	{ }
};

DEFINE_DT_DRIVER(imx_pinctrl_dt_driver) = {
	.name = "imx_pinctrl",
	.type = DT_DRIVER_PINCTRL,
	.match_table = imx_pinctrl_match_table,
	.probe = imx_pinctrl_probe,
};
