// SPDX-License-Identifier: BSD-2-Clause
/*
 * Copyright (c) 2026, Qualcomm Technologies, Inc.
 */

#include <hwkm.h>
#include <hwkm_errno.h>
#include <hwkm_regs.h>
#include <initcall.h>
#include <io.h>
#include <kernel/mutex.h>
#include <kernel/panic.h>
#include <kernel/tee_common_otp.h>
#include <malloc.h>
#include <mm/core_memprot.h>
#include <mm/core_mmu.h>
#include <platform_config.h>
#include <stdlib_ext.h>
#include <string_ext.h>
#include <trace.h>
#include <util.h>

register_phys_mem_pgdir(MEM_AREA_IO_SEC, HWKM_MASTER_BASE, HWKM_MASTER_SIZE);

static_assert(HW_UNIQUE_KEY_LENGTH <= HWKM_MAX_KEY_SIZE);

#define HWKM_BBAC_BIT(slot) BIT((slot) % 32)

#define HWKM_BANK0_BBAC_0 \
	(HWKM_BBAC_BIT(HWKM_SLOT_TZ_NKDK_L2)                 | \
	 HWKM_BBAC_BIT(HWKM_SLOT_TZ_PKDK_L2)                 | \
	 HWKM_BBAC_BIT(HWKM_SLOT_TZ_SKDK_L2)                 | \
	 HWKM_BBAC_BIT(HWKM_SLOT_TZ_UKDK_L2)                 | \
	 HWKM_BBAC_BIT(HWKM_SLOT_TPKEY_SLOT)                 | \
	 HWKM_BBAC_BIT(HWKM_SLOT_TPKEY_ODD_SLOT)             | \
	 HWKM_BBAC_BIT(HWKM_SLOT_TZ_SWAP_KEY_SLOT)           | \
	 HWKM_BBAC_BIT(HWKM_SLOT_TZ_SWAP_KEY_ODD_SLOT)       | \
	 HWKM_BBAC_BIT(HWKM_SLOT_TZ_WRAP_KEY_SLOT)           | \
	 HWKM_BBAC_BIT(HWKM_SLOT_TZ_WRAP_KEY_ODD_SLOT)       | \
	 HWKM_BBAC_BIT(HWKM_SLOT_TZ_GENERAL_PURPOSE_SLOT1)   | \
	 HWKM_BBAC_BIT(HWKM_SLOT_TZ_GENERAL_PURPOSE_SLOT2)   | \
	 HWKM_BBAC_BIT(HWKM_SLOT_PERSISTENT_SHARED_SLOT_PAIR1)     | \
	 HWKM_BBAC_BIT(HWKM_SLOT_PERSISTENT_SHARED_SLOT_PAIR1_ODD) | \
	 HWKM_BBAC_BIT(HWKM_SLOT_PERSISTENT_SHARED_SLOT_PAIR2)     | \
	 HWKM_BBAC_BIT(HWKM_SLOT_PERSISTENT_SHARED_SLOT_PAIR2_ODD) | \
	 HWKM_BBAC_BIT(HWKM_SLOT_TZ_MIXING_KEY_SLOT))

static struct hwkm_drv_ctx hwkm_ctx = {
	.hwkm_lock = MUTEX_INITIALIZER,
};

struct hwkm_drv_ctx *hwkm_get_context(void)
{
	return hwkm_ctx.initialized ? &hwkm_ctx : NULL;
}

struct hwkm_transaction *hwkm_transaction_alloc(void)
{
	return calloc(1, sizeof(struct hwkm_transaction));
}

void hwkm_transaction_free(struct hwkm_transaction *t)
{
	free_wipe(t);
}

#define HWKM_ERR_ENTRY(m) { .status = (m), .name = #m }

static const struct { uint32_t status; const char *name; } hwkm_err_table[] = {
	/* Common errors. */
	HWKM_ERR_ENTRY(HWKM_ERR_RSP_FIFO_UNDERFLOW),
	HWKM_ERR_ENTRY(HWKM_ERR_CMD_FIFO_OVERFLOW),
	HWKM_ERR_ENTRY(HWKM_ERR_OPCODE_UNSUPPORTED),
	HWKM_ERR_ENTRY(HWKM_ERR_INVALID_OPCODE),
	HWKM_ERR_ENTRY(HWKM_ERR_INCORRECT_CMD_LENGTH),
	HWKM_ERR_ENTRY(HWKM_ERR_CRC_CHECK),
	HWKM_ERR_ENTRY(HWKM_ERR_BBAC_ACCESS),
	/* NIST_KEYGEN errors. */
	HWKM_ERR_ENTRY(HWKM_NIST_KEYGEN_ERR_KEYSLOT_ID_OUT_OF_RANGE),
	HWKM_ERR_ENTRY(HWKM_NIST_KEYGEN_ERR_UNSUPPORTED_KEY_SIZE),
	HWKM_ERR_ENTRY(HWKM_NIST_KEYGEN_ERR_KT_PARITY),
	HWKM_ERR_ENTRY(HWKM_NIST_KEYGEN_ERR_INVALID_KEY_TYPE),
	HWKM_ERR_ENTRY(HWKM_NIST_KEYGEN_ERR_INVALID_ALG_ALLOWED),
	HWKM_ERR_ENTRY(HWKM_NIST_KEYGEN_ERR_INVALID_KEY_ATTRIB),
	HWKM_ERR_ENTRY(HWKM_NIST_KEYGEN_ERR_INVALID_TPKEY_ATTRIB),
	HWKM_ERR_ENTRY(HWKM_NIST_KEYGEN_ERR_INVALID_KSK_ATTRIB),
	HWKM_ERR_ENTRY(HWKM_NIST_KEYGEN_ERR_INVALID_KWK_ATTRIB),
	HWKM_ERR_ENTRY(HWKM_NIST_KEYGEN_ERR_INVALID_KDF_DEPTH),
	HWKM_ERR_ENTRY(HWKM_NIST_KEYGEN_ERR_INVALID_SECURITY_LEVEL),
	HWKM_ERR_ENTRY(HWKM_NIST_KEYGEN_ERR_DKS_SLOT_NOT_EMPTY),
	HWKM_ERR_ENTRY(HWKM_NIST_KEYGEN_ERR_ACCESS_VIOLATION),
	/* KEY_SLOT_RDWR errors. */
	HWKM_ERR_ENTRY(HWKM_KEY_SLOT_RDWR_ERR_KEYSLOT_ID_OUT_OF_RANGE),
	HWKM_ERR_ENTRY(HWKM_KEY_SLOT_RDWR_ERR_UNSUPPORTED_KEY_SIZE),
	HWKM_ERR_ENTRY(HWKM_KEY_SLOT_RDWR_ERR_KT_PARITY),
	HWKM_ERR_ENTRY(HWKM_KEY_SLOT_RDWR_ERR_INVALID_SECURITY_LEVEL),
	HWKM_ERR_ENTRY(HWKM_KEY_SLOT_RDWR_ERR_INVALID_KEY_TYPE),
	HWKM_ERR_ENTRY(HWKM_KEY_SLOT_RDWR_ERR_INVALID_ALG_ALLOWED),
	HWKM_ERR_ENTRY(HWKM_KEY_SLOT_RDWR_ERR_INVALID_KEY_ATTRIB),
	HWKM_ERR_ENTRY(HWKM_KEY_SLOT_RDWR_ERR_INVALID_TPKEY_ATTRIB),
	HWKM_ERR_ENTRY(HWKM_KEY_SLOT_RDWR_ERR_INVALID_KSK_ATTRIB),
	HWKM_ERR_ENTRY(HWKM_KEY_SLOT_RDWR_ERR_INVALID_KWK_ATTRIB),
	HWKM_ERR_ENTRY(HWKM_KEY_SLOT_RDWR_ERR_INVALID_KDF_DEPTH),
	HWKM_ERR_ENTRY(HWKM_KEY_SLOT_RDWR_ERR_SECURITY_LEVEL_VIOLATION),
	HWKM_ERR_ENTRY(HWKM_KEY_SLOT_RDWR_ERR_SKS_SLOT_EMPTY),
	HWKM_ERR_ENTRY(HWKM_KEY_SLOT_RDWR_ERR_DKS_SLOT_NOT_EMPTY),
	HWKM_ERR_ENTRY(HWKM_KEY_SLOT_RDWR_ERR_ACCESS_VIOLATION),
	/* SYSTEM_KDF errors. */
	HWKM_ERR_ENTRY(HWKM_SYSTEM_KDF_ERR_FR_RD_ERR_ON_SLAVE),
	HWKM_ERR_ENTRY(HWKM_SYSTEM_KDF_ERR_MKS_L1L2_NOT_ALLOWED),
	HWKM_ERR_ENTRY(HWKM_SYSTEM_KDF_ERR_SEC_CTRL_ACCESS),
	HWKM_ERR_ENTRY(HWKM_SYSTEM_KDF_ERR_KT_PARITY),
	HWKM_ERR_ENTRY(HWKM_SYSTEM_KDF_ERR_BSVE_BIT_NOT_SUPPORTED),
	HWKM_ERR_ENTRY(HWKM_SYSTEM_KDF_ERR_INVALID_SECURITY_LEVEL),
	HWKM_ERR_ENTRY(HWKM_SYSTEM_KDF_ERR_INVALID_KEY_TYPE),
	HWKM_ERR_ENTRY(HWKM_SYSTEM_KDF_ERR_INVALID_ALG_ALLOWED),
	HWKM_ERR_ENTRY(HWKM_SYSTEM_KDF_ERR_SWAP_EXPORT_NOT_ALLOWED),
	HWKM_ERR_ENTRY(HWKM_SYSTEM_KDF_ERR_KEYPOLICY_CONSISTENCY),
	HWKM_ERR_ENTRY(HWKM_SYSTEM_KDF_ERR_ENCRYPT_NOT_ALLOWED),
	HWKM_ERR_ENTRY(HWKM_SYSTEM_KDF_ERR_UNEXPECTED_ALG_ALLOWED),
	HWKM_ERR_ENTRY(HWKM_SYSTEM_KDF_ERR_UNEXPECTED_KEY_TYPE),
	HWKM_ERR_ENTRY(HWKM_SYSTEM_KDF_ERR_KDF_DEPTH_ERROR),
	HWKM_ERR_ENTRY(HWKM_SYSTEM_KDF_ERR_KDK_TYPE),
	HWKM_ERR_ENTRY(HWKM_SYSTEM_KDF_ERR_KEY_SIZE),
	HWKM_ERR_ENTRY(HWKM_SYSTEM_KDF_ERR_KEYSLOT_SLOT),
	HWKM_ERR_ENTRY(HWKM_SYSTEM_KDF_ERR_KEYSLOT_OUT_OF_RANGE),
	HWKM_ERR_ENTRY(HWKM_SYSTEM_KDF_ERR_DOUBLE_KEY_SLOT_NOT_EVEN),
	HWKM_ERR_ENTRY(HWKM_SYSTEM_KDF_ERR_ACCESS_VIOLATION),
	HWKM_ERR_ENTRY(HWKM_SYSTEM_KDF_ERR_SECURITY_LEVEL_VIOLATION),
	/* KEY_WRAP_EXPORT errors. */
	HWKM_ERR_ENTRY(HWKM_EXPORT_ERR_KWK_DOUBLE_KEY_ODD_SLOT),
	HWKM_ERR_ENTRY(HWKM_EXPORT_ERR_ENCRYPT_NOT_ALLOWED),
	HWKM_ERR_ENTRY(HWKM_EXPORT_ERR_SKS_SIZE_ERROR),
	HWKM_ERR_ENTRY(HWKM_EXPORT_ERR_SKS_SLOT_OUT_OF_RANGE),
	HWKM_ERR_ENTRY(HWKM_EXPORT_ERR_KWK_SIZE_ERROR),
	HWKM_ERR_ENTRY(HWKM_EXPORT_ERR_KWK_SLOT_OUT_OF_RANGE),
	HWKM_ERR_ENTRY(HWKM_EXPORT_ERR_KT_PARITY),
	HWKM_ERR_ENTRY(HWKM_EXPORT_ERR_WRAP_WITH_TPKEY_NOT_ALLOWED),
	HWKM_ERR_ENTRY(HWKM_EXPORT_ERR_SWAP_EXPORT_NOT_ALLOWED),
	HWKM_ERR_ENTRY(HWKM_EXPORT_ERR_WRAP_EXPORT_NOT_ALLOWED),
	HWKM_ERR_ENTRY(HWKM_EXPORT_ERR_UNEXPECTED_ALG_ALLOWED),
	HWKM_ERR_ENTRY(HWKM_EXPORT_ERR_SECURITY_LEVEL_ERROR),
	HWKM_ERR_ENTRY(HWKM_EXPORT_ERR_UNEXPECTED_KEY_TYPE),
	HWKM_ERR_ENTRY(HWKM_EXPORT_ERR_KWK_SLOT_EMPTY),
	HWKM_ERR_ENTRY(HWKM_EXPORT_ERR_SKS_SLOT_EMPTY),
	HWKM_ERR_ENTRY(HWKM_EXPORT_ERR_SKS_ACCESS_VIOLATION),
	HWKM_ERR_ENTRY(HWKM_EXPORT_ERR_KWK_ACCESS_VIOLATION),
	/* KEY_UNWRAP_IMPORT errors. */
	HWKM_ERR_ENTRY(HWKM_IMPORT_ERR_UNWRAP_FAILED),
	HWKM_ERR_ENTRY(HWKM_IMPORT_ERR_KWK_DOUBLE_KEY_ODD_SLOT),
	HWKM_ERR_ENTRY(HWKM_IMPORT_ERR_KWK_SIZE_ERROR),
	HWKM_ERR_ENTRY(HWKM_IMPORT_ERR_DKS_SIZE_ERROR),
	HWKM_ERR_ENTRY(HWKM_IMPORT_ERR_DKS_OUT_OF_RANGE),
	HWKM_ERR_ENTRY(HWKM_IMPORT_ERR_KWK_SLOT_OUT_OF_RANGE),
	HWKM_ERR_ENTRY(HWKM_IMPORT_ERR_KT_PARITY),
	HWKM_ERR_ENTRY(HWKM_IMPORT_ERR_SECURITY_LEVEL_ERROR),
	HWKM_ERR_ENTRY(HWKM_IMPORT_ERR_INVALID_SECURITY_LEVEL),
	HWKM_ERR_ENTRY(HWKM_IMPORT_ERR_INVALID_KEY_TYPE),
	HWKM_ERR_ENTRY(HWKM_IMPORT_ERR_INVALID_ALG_ALLOWED),
	HWKM_ERR_ENTRY(HWKM_IMPORT_ERR_CONSISTENCY_CHECK_FAILED),
	HWKM_ERR_ENTRY(HWKM_IMPORT_ERR_INVALID_TPKEY_ATTRIB),
	HWKM_ERR_ENTRY(HWKM_IMPORT_ERR_INVALID_KSK_ATTRIB),
	HWKM_ERR_ENTRY(HWKM_IMPORT_ERR_INVALID_KWK_ATTRIB),
	HWKM_ERR_ENTRY(HWKM_IMPORT_ERR_INVALID_KDF_DEPTH),
	HWKM_ERR_ENTRY(HWKM_IMPORT_ERR_DECRYPT_NOT_ALLOWED),
	HWKM_ERR_ENTRY(HWKM_IMPORT_ERR_UNEXPECTED_ALG_ALLOWED),
	HWKM_ERR_ENTRY(HWKM_IMPORT_ERR_UNEXPECTED_KEY_TYPE),
	HWKM_ERR_ENTRY(HWKM_IMPORT_ERR_KWK_SLOT_EMPTY),
	HWKM_ERR_ENTRY(HWKM_IMPORT_ERR_DKS_SLOT_NOT_EMPTY),
	HWKM_ERR_ENTRY(HWKM_IMPORT_ERR_DKS_ACCESS_VIOLATION),
	HWKM_ERR_ENTRY(HWKM_IMPORT_ERR_KWK_ACCESS_VIOLATION),
	/* KEY_SLOT_CLEAR errors. */
	HWKM_ERR_ENTRY(HWKM_CLEAR_ERR_KEYSLOT_ID_NOT_ACCESSIBLE),
	HWKM_ERR_ENTRY(HWKM_CLEAR_ERR_KEYSLOT_ID_OUT_OF_RANGE),
	HWKM_ERR_ENTRY(HWKM_CLEAR_ERR_KEY_SIZE),
	HWKM_ERR_ENTRY(HWKM_CLEAR_ERR_DOUBLE_KEY_DKS_SLOT_NOT_EVEN),
	HWKM_ERR_ENTRY(HWKM_CLEAR_ERR_DKS_SLOT_EMPTY),
	HWKM_ERR_ENTRY(HWKM_CLEAR_ERR_ACCESS_VIOLATION),
	/* SET_TPKEY errors. */
	HWKM_ERR_ENTRY(HWKM_TPKEY_ERR_KT_PARITY),
	HWKM_ERR_ENTRY(HWKM_TPKEY_ERR_DOUBLE_KEY_SLOT_NOT_EVEN),
	HWKM_ERR_ENTRY(HWKM_TPKEY_ERR_WRONG_KEY_SIZE),
	HWKM_ERR_ENTRY(HWKM_TPKEY_ERR_KEYSLOT_ID_OUT_OF_RANGE),
	HWKM_ERR_ENTRY(HWKM_TPKEY_ERR_UNEXPECTED_KEY_TYPE),
	HWKM_ERR_ENTRY(HWKM_TPKEY_ERR_SKS_SLOT_EMPTY),
	HWKM_ERR_ENTRY(HWKM_TPKEY_ERR_ACCESS_VIOLATION),
};

const char *hwkm_err2str(uint32_t status)
{
	size_t i = 0;

	for (i = 0; i < ARRAY_SIZE(hwkm_err_table); i++)
		if (hwkm_err_table[i].status == status)
			return hwkm_err_table[i].name;

	return "Unknown";
}

static TEE_Result hwkm_init(void)
{
	uint32_t status = 0;
	vaddr_t base = 0;

	base = (vaddr_t)phys_to_virt(HWKM_MASTER_BASE, MEM_AREA_IO_SEC,
				     HWKM_MASTER_SIZE);
	if (!base)
		return TEE_ERROR_GENERIC;

	/* Check the hardware self-test status. */
	status = io_read32_off(base, HWKM_TZ_KM_STATUS);
	if (status & (HWKM_TZ_KM_STATUS_BIST_ERROR |
		      HWKM_TZ_KM_STATUS_CRYPTO_LIB_BIST_ERROR)) {
		EMSG("hwkm: BIST failed, status=0x%08"PRIx32, status);
		return TEE_ERROR_GENERIC;
	}

	/* Disable CRC checking on command packets. */
	io_write32_off_field(base, HWKM_TZ_KM_CTL,
			     HWKM_TZ_KM_CTL_CRC_CHECK_EN, 0);

	io_write32_off(base, HWKM_BANK0_AC + HWKM_BANKn_AC_BBAC_0,
		       HWKM_BANK0_BBAC_0);
	io_write32_off(base, HWKM_BANK0_AC + HWKM_BANKn_AC_BBAC_1, 0);
	io_write32_off(base, HWKM_BANK0_AC + HWKM_BANKn_AC_BBAC_2, 0);
	io_write32_off(base, HWKM_BANK0_AC + HWKM_BANKn_AC_BBAC_3, 0);
	io_write32_off(base, HWKM_BANK0_AC + HWKM_BANKn_AC_BBAC_4, 0);

	/*
	 * Clear the spurious RSP_FIFO_FULL sticky bit.
	 * HW errata QCTDD06252768: RSP_FIFO_FULL may be set after reset even
	 * though the FIFO is empty. Write 1 to clear it unconditionally so
	 * it does not interfere with CMD_DONE polling in
	 * master_run_transaction().
	 */
	io_write32_off(base, HWKM_BANK0_KM_IRQ_STATUS,
		       HWKM_BANK0_KM_IRQ_STATUS_RSP_FIFO_FULL);

	hwkm_ctx.base = base;
	hwkm_ctx.initialized = true;

	return TEE_SUCCESS;
}

static TEE_Result hwkm_driver_init(void)
{
	struct tee_hw_unique_key huk = { };
	TEE_Result res = TEE_ERROR_GENERIC;

	res = hwkm_init();
	if (res) {
		EMSG("hwkm: init failed: 0x%08"PRIx32, res);
		return res;
	}

	res = tee_otp_get_hw_unique_key(&huk);
	if (res) {
		EMSG("hwkm: HUK derivation failed: 0x%08"PRIx32, res);
		panic("HWKM HUK derivation failure");
	}

	memzero_explicit(&huk, sizeof(huk));

	return TEE_SUCCESS;
}

service_init(hwkm_driver_init);
