$(call force,CFG_TEE_CORE_NB_CORE,4)
CFG_NUM_THREADS ?= 4

CFG_QCOM_DIAG_LOG ?= $(CFG_TEE_CORE_DEBUG)

CFG_TZDRAM_START ?= 0x87D80000
CFG_TZDRAM_SIZE ?= 0x280000
# Reserve the TMEL IPC coherent carveout at the end of TZDRAM.
ifeq ($(CFG_QCOM_TMEL_COM),y)
CFG_TEE_RAM_VA_SIZE ?= (0x280000 - $(CFG_TMECOM_IPCBUF_CARVEOUT_SIZE))
else
CFG_TEE_RAM_VA_SIZE ?= 0x280000
endif
