/* SPDX-License-Identifier: BSD-2-Clause */
/*
 * Copyright (c) 2026, Qualcomm Technologies, Inc.
 *
 * Hardware Key Manager (HWKM) response-error bit definitions.
 */

#ifndef __HWKM_ERRNO_H__
#define __HWKM_ERRNO_H__

#include <util.h>

/* Error status bitmap at RSP[*_RSP_ERR_IDX]. */

#define HWKM_RSP_ERR_SUCCESS                            0U
/* Common errors (bits 0 - 7, present in every opcode response). */
#define HWKM_ERR_RSP_FIFO_UNDERFLOW			BIT(0)
#define HWKM_ERR_CMD_FIFO_OVERFLOW			BIT(1)
#define HWKM_ERR_OPCODE_UNSUPPORTED			BIT(2)
#define HWKM_ERR_INVALID_OPCODE				BIT(3)
#define HWKM_ERR_INCORRECT_CMD_LENGTH			BIT(4)
#define HWKM_ERR_CRC_CHECK				BIT(5)
#define HWKM_ERR_BBAC_ACCESS				BIT(6)

/* NIST_KEYGEN specific errors (bits 8+). */
#define HWKM_NIST_KEYGEN_ERR_KEYSLOT_ID_OUT_OF_RANGE	BIT(8)
#define HWKM_NIST_KEYGEN_ERR_UNSUPPORTED_KEY_SIZE	BIT(9)
#define HWKM_NIST_KEYGEN_ERR_KT_PARITY			BIT(10)
#define HWKM_NIST_KEYGEN_ERR_INVALID_KEY_TYPE		BIT(11)
#define HWKM_NIST_KEYGEN_ERR_INVALID_ALG_ALLOWED	BIT(12)
#define HWKM_NIST_KEYGEN_ERR_INVALID_KEY_ATTRIB BIT(13)
#define HWKM_NIST_KEYGEN_ERR_INVALID_TPKEY_ATTRIB	BIT(14)
#define HWKM_NIST_KEYGEN_ERR_INVALID_KSK_ATTRIB		BIT(15)
#define HWKM_NIST_KEYGEN_ERR_INVALID_KWK_ATTRIB		BIT(16)
#define HWKM_NIST_KEYGEN_ERR_INVALID_KDF_DEPTH		BIT(17)
#define HWKM_NIST_KEYGEN_ERR_INVALID_SECURITY_LEVEL	BIT(18)
#define HWKM_NIST_KEYGEN_ERR_DKS_SLOT_NOT_EMPTY		BIT(19)
#define HWKM_NIST_KEYGEN_ERR_ACCESS_VIOLATION		BIT(20)

/* KEY_SLOT_RDWR specific errors (bits 8+). */
#define HWKM_KEY_SLOT_RDWR_ERR_KEYSLOT_ID_OUT_OF_RANGE	BIT(8)
#define HWKM_KEY_SLOT_RDWR_ERR_UNSUPPORTED_KEY_SIZE	BIT(9)
#define HWKM_KEY_SLOT_RDWR_ERR_KT_PARITY		BIT(10)
#define HWKM_KEY_SLOT_RDWR_ERR_INVALID_SECURITY_LEVEL	BIT(11)
#define HWKM_KEY_SLOT_RDWR_ERR_INVALID_KEY_TYPE		BIT(12)
#define HWKM_KEY_SLOT_RDWR_ERR_INVALID_ALG_ALLOWED	BIT(13)
#define HWKM_KEY_SLOT_RDWR_ERR_INVALID_KEY_ATTRIB BIT(14)
#define HWKM_KEY_SLOT_RDWR_ERR_INVALID_TPKEY_ATTRIB	BIT(15)
#define HWKM_KEY_SLOT_RDWR_ERR_INVALID_KSK_ATTRIB	BIT(16)
#define HWKM_KEY_SLOT_RDWR_ERR_INVALID_KWK_ATTRIB	BIT(17)
#define HWKM_KEY_SLOT_RDWR_ERR_INVALID_KDF_DEPTH	BIT(18)
#define HWKM_KEY_SLOT_RDWR_ERR_SECURITY_LEVEL_VIOLATION	BIT(19)
#define HWKM_KEY_SLOT_RDWR_ERR_SKS_SLOT_EMPTY		BIT(20)
#define HWKM_KEY_SLOT_RDWR_ERR_DKS_SLOT_NOT_EMPTY	BIT(21)
#define HWKM_KEY_SLOT_RDWR_ERR_ACCESS_VIOLATION		BIT(22)

/* SYSTEM_KDF specific errors (bits 8+). */
#define HWKM_SYSTEM_KDF_ERR_FR_RD_ERR_ON_SLAVE		BIT(8)
#define HWKM_SYSTEM_KDF_ERR_MKS_L1L2_NOT_ALLOWED	BIT(9)
#define HWKM_SYSTEM_KDF_ERR_SEC_CTRL_ACCESS		BIT(10)
#define HWKM_SYSTEM_KDF_ERR_KT_PARITY			BIT(11)
#define HWKM_SYSTEM_KDF_ERR_BSVE_BIT_NOT_SUPPORTED	BIT(12)
#define HWKM_SYSTEM_KDF_ERR_INVALID_SECURITY_LEVEL	BIT(13)
#define HWKM_SYSTEM_KDF_ERR_INVALID_KEY_TYPE		BIT(14)
#define HWKM_SYSTEM_KDF_ERR_INVALID_ALG_ALLOWED		BIT(15)
#define HWKM_SYSTEM_KDF_ERR_SWAP_EXPORT_NOT_ALLOWED	BIT(16)
#define HWKM_SYSTEM_KDF_ERR_KEYPOLICY_CONSISTENCY	BIT(17)
#define HWKM_SYSTEM_KDF_ERR_ENCRYPT_NOT_ALLOWED		BIT(18)
#define HWKM_SYSTEM_KDF_ERR_UNEXPECTED_ALG_ALLOWED	BIT(19)
#define HWKM_SYSTEM_KDF_ERR_UNEXPECTED_KEY_TYPE		BIT(20)
#define HWKM_SYSTEM_KDF_ERR_KDF_DEPTH_ERROR		BIT(21)
#define HWKM_SYSTEM_KDF_ERR_KDK_TYPE			BIT(22)
#define HWKM_SYSTEM_KDF_ERR_KEY_SIZE			BIT(23)
#define HWKM_SYSTEM_KDF_ERR_KEYSLOT_SLOT		BIT(24)
#define HWKM_SYSTEM_KDF_ERR_KEYSLOT_OUT_OF_RANGE	BIT(25)
#define HWKM_SYSTEM_KDF_ERR_DOUBLE_KEY_SLOT_NOT_EVEN	BIT(26)
#define HWKM_SYSTEM_KDF_ERR_ACCESS_VIOLATION		BIT(27)
#define HWKM_SYSTEM_KDF_ERR_SECURITY_LEVEL_VIOLATION	BIT(28)

/* KEY_WRAP_EXPORT specific errors (bits 8+). */
#define HWKM_EXPORT_ERR_KWK_DOUBLE_KEY_ODD_SLOT		BIT(8)
#define HWKM_EXPORT_ERR_ENCRYPT_NOT_ALLOWED		BIT(9)
#define HWKM_EXPORT_ERR_SKS_SIZE_ERROR			BIT(10)
#define HWKM_EXPORT_ERR_SKS_SLOT_OUT_OF_RANGE		BIT(11)
#define HWKM_EXPORT_ERR_KWK_SIZE_ERROR			BIT(12)
#define HWKM_EXPORT_ERR_KWK_SLOT_OUT_OF_RANGE		BIT(13)
#define HWKM_EXPORT_ERR_KT_PARITY			BIT(14)
#define HWKM_EXPORT_ERR_WRAP_WITH_TPKEY_NOT_ALLOWED	BIT(15)
#define HWKM_EXPORT_ERR_SWAP_EXPORT_NOT_ALLOWED		BIT(16)
#define HWKM_EXPORT_ERR_WRAP_EXPORT_NOT_ALLOWED		BIT(17)
#define HWKM_EXPORT_ERR_UNEXPECTED_ALG_ALLOWED		BIT(18)
#define HWKM_EXPORT_ERR_SECURITY_LEVEL_ERROR		BIT(19)
#define HWKM_EXPORT_ERR_UNEXPECTED_KEY_TYPE		BIT(20)
#define HWKM_EXPORT_ERR_KWK_SLOT_EMPTY			BIT(21)
#define HWKM_EXPORT_ERR_SKS_SLOT_EMPTY			BIT(22)
#define HWKM_EXPORT_ERR_SKS_ACCESS_VIOLATION		BIT(23)
#define HWKM_EXPORT_ERR_KWK_ACCESS_VIOLATION		BIT(24)

/* KEY_UNWRAP_IMPORT specific errors (bits 8+). */
#define HWKM_IMPORT_ERR_UNWRAP_FAILED			BIT(8)
#define HWKM_IMPORT_ERR_KWK_DOUBLE_KEY_ODD_SLOT		BIT(9)
#define HWKM_IMPORT_ERR_KWK_SIZE_ERROR			BIT(10)
#define HWKM_IMPORT_ERR_DKS_SIZE_ERROR			BIT(11)
#define HWKM_IMPORT_ERR_DKS_OUT_OF_RANGE		BIT(12)
#define HWKM_IMPORT_ERR_KWK_SLOT_OUT_OF_RANGE		BIT(13)
#define HWKM_IMPORT_ERR_KT_PARITY			BIT(14)
#define HWKM_IMPORT_ERR_SECURITY_LEVEL_ERROR		BIT(15)
#define HWKM_IMPORT_ERR_INVALID_SECURITY_LEVEL		BIT(16)
#define HWKM_IMPORT_ERR_INVALID_KEY_TYPE		BIT(17)
#define HWKM_IMPORT_ERR_INVALID_ALG_ALLOWED		BIT(18)
#define HWKM_IMPORT_ERR_CONSISTENCY_CHECK_FAILED	BIT(19)
#define HWKM_IMPORT_ERR_INVALID_TPKEY_ATTRIB		BIT(20)
#define HWKM_IMPORT_ERR_INVALID_KSK_ATTRIB		BIT(21)
#define HWKM_IMPORT_ERR_INVALID_KWK_ATTRIB		BIT(22)
#define HWKM_IMPORT_ERR_INVALID_KDF_DEPTH		BIT(23)
#define HWKM_IMPORT_ERR_DECRYPT_NOT_ALLOWED		BIT(24)
#define HWKM_IMPORT_ERR_UNEXPECTED_ALG_ALLOWED		BIT(25)
#define HWKM_IMPORT_ERR_UNEXPECTED_KEY_TYPE		BIT(26)
#define HWKM_IMPORT_ERR_KWK_SLOT_EMPTY			BIT(27)
#define HWKM_IMPORT_ERR_DKS_SLOT_NOT_EMPTY		BIT(28)
#define HWKM_IMPORT_ERR_DKS_ACCESS_VIOLATION		BIT(29)
#define HWKM_IMPORT_ERR_KWK_ACCESS_VIOLATION		BIT(30)

/* KEY_SLOT_CLEAR specific errors (bits 8+). */
#define HWKM_CLEAR_ERR_KEYSLOT_ID_NOT_ACCESSIBLE	BIT(8)
#define HWKM_CLEAR_ERR_KEYSLOT_ID_OUT_OF_RANGE		BIT(9)
#define HWKM_CLEAR_ERR_KEY_SIZE				BIT(10)
#define HWKM_CLEAR_ERR_DOUBLE_KEY_DKS_SLOT_NOT_EVEN	BIT(11)
#define HWKM_CLEAR_ERR_DKS_SLOT_EMPTY			BIT(12)
#define HWKM_CLEAR_ERR_ACCESS_VIOLATION			BIT(13)

/* SET_TPKEY specific errors (bits 8+). */
#define HWKM_TPKEY_ERR_KT_PARITY			BIT(8)
#define HWKM_TPKEY_ERR_DOUBLE_KEY_SLOT_NOT_EVEN		BIT(9)
#define HWKM_TPKEY_ERR_WRONG_KEY_SIZE			BIT(10)
#define HWKM_TPKEY_ERR_KEYSLOT_ID_OUT_OF_RANGE		BIT(11)
#define HWKM_TPKEY_ERR_UNEXPECTED_KEY_TYPE		BIT(12)
#define HWKM_TPKEY_ERR_SKS_SLOT_EMPTY			BIT(13)
#define HWKM_TPKEY_ERR_ACCESS_VIOLATION			BIT(14)

const char *hwkm_err2str(uint32_t status);

#endif /* __HWKM_ERRNO_H__ */
