/* SPDX-License-Identifier: BSD-3-Clause */
/*
 * Copyright (C) Foundries Ltd. 2020 - All Rights Reserved
 * Author: Jorge Ramirez <jorge@foundries.io>
 *
 * Configuration file for the SDK/Middleware (enables/disable Middleware
 * features)
 *
 */

#ifndef SSS_APIS_INC_FSL_SSS_FTR_H_
#define SSS_APIS_INC_FSL_SSS_FTR_H_

#define SSS_HAVE_APPLET_NONE 0
#define SSS_HAVE_APPLET_A71CH 0
#define SSS_HAVE_APPLET_A71CL 0
#define SSS_HAVE_APPLET_A71CH_SIM 0
#define SSS_HAVE_APPLET_SE05X_A 0
#define SSS_HAVE_APPLET_SE05X_B 0
#define SSS_HAVE_APPLET_SE05X_C 1
#define SSS_HAVE_APPLET_SE05X_L 0
#define SSS_HAVE_APPLET_LOOPBACK 0

#if ((0				\
+ SSS_HAVE_APPLET_NONE		\
+ SSS_HAVE_APPLET_A71CH		\
+ SSS_HAVE_APPLET_A71CL		\
+ SSS_HAVE_APPLET_A71CH_SIM	\
+ SSS_HAVE_APPLET_SE05X_A	\
+ SSS_HAVE_APPLET_SE05X_B	\
+ SSS_HAVE_APPLET_SE05X_C	\
+ SSS_HAVE_APPLET_SE05X_L	\
+ SSS_HAVE_APPLET_LOOPBACK	\
) > 1)
#error "Enable only one of 'Applet'"
#endif

#if ((0				\
+ SSS_HAVE_APPLET_NONE		\
+ SSS_HAVE_APPLET_A71CH		\
+ SSS_HAVE_APPLET_A71CL		\
+ SSS_HAVE_APPLET_A71CH_SIM	\
+ SSS_HAVE_APPLET_SE05X_A	\
+ SSS_HAVE_APPLET_SE05X_B	\
+ SSS_HAVE_APPLET_SE05X_C	\
+ SSS_HAVE_APPLET_SE05X_L	\
+ SSS_HAVE_APPLET_LOOPBACK	\
) == 0)
#error "Enable at-least one of 'Applet'"
#endif

#define SSS_HAVE_SE05X_VER_03_XX 1
#define SSS_HAVE_SE05X_VER_04_04 0
#define SSS_HAVE_SE05X_VER_04_08 0
#define SSS_HAVE_SE05X_VER_04_12 0

#if ((0				\
+ SSS_HAVE_SE05X_VER_03_XX	\
+ SSS_HAVE_SE05X_VER_04_04	\
+ SSS_HAVE_SE05X_VER_04_08	\
+ SSS_HAVE_SE05X_VER_04_12	\
) > 1)
#error "Enable only one of 'SE05X_Ver'"
#endif

#if ((0				\
+ SSS_HAVE_SE05X_VER_03_XX	\
+ SSS_HAVE_SE05X_VER_04_04	\
+ SSS_HAVE_SE05X_VER_04_08	\
+ SSS_HAVE_SE05X_VER_04_12	\
) == 0)
#error "Enable at-least one of 'SE05X_Ver'"
#endif

#define SSS_HAVE_HOSTCRYPTO_MBEDTLS 0
#define SSS_HAVE_HOSTCRYPTO_MBEDCRYPTO 0
#define SSS_HAVE_HOSTCRYPTO_OPENSSL 0
#define SSS_HAVE_HOSTCRYPTO_USER 1

#define SSS_HAVE_HOSTCRYPTO_NONE 0

#if ((0					\
+ SSS_HAVE_HOSTCRYPTO_MBEDTLS		\
+ SSS_HAVE_HOSTCRYPTO_MBEDCRYPTO	\
+ SSS_HAVE_HOSTCRYPTO_OPENSSL		\
+ SSS_HAVE_HOSTCRYPTO_USER		\
+ SSS_HAVE_HOSTCRYPTO_NONE		\
) > 1)
#error "Enable only one of 'HostCrypto'"
#endif

#if ((0					\
+ SSS_HAVE_HOSTCRYPTO_MBEDTLS		\
+ SSS_HAVE_HOSTCRYPTO_MBEDCRYPTO	\
+ SSS_HAVE_HOSTCRYPTO_OPENSSL		\
+ SSS_HAVE_HOSTCRYPTO_USER		\
+ SSS_HAVE_HOSTCRYPTO_NONE		\
) == 0)
#error "Enable at-least one of 'HostCrypto'"
#endif

#define SSS_HAVE_MBEDTLS_ALT_SSS 0
#define SSS_HAVE_MBEDTLS_ALT_A71CH 0
#define SSS_HAVE_MBEDTLS_ALT_NONE 1

#if ((0					\
+ SSS_HAVE_MBEDTLS_ALT_SSS		\
+ SSS_HAVE_MBEDTLS_ALT_A71CH		\
+ SSS_HAVE_MBEDTLS_ALT_NONE		\
) > 1)
#error "Enable only one of 'mbedTLS_ALT'"
#endif

#if ((0					\
+ SSS_HAVE_MBEDTLS_ALT_SSS		\
+ SSS_HAVE_MBEDTLS_ALT_A71CH		\
+ SSS_HAVE_MBEDTLS_ALT_NONE		\
) == 0)
#error "Enable at-least one of 'mbedTLS_ALT'"
#endif

#define SSS_HAVE_SCP_NONE 0
#define SSS_HAVE_SCP_SCP03_SSS 1
#define SSS_HAVE_SCP_SCP03_HOSTCRYPTO 0

#if ((0					\
+ SSS_HAVE_SCP_NONE			\
+ SSS_HAVE_SCP_SCP03_SSS		\
+ SSS_HAVE_SCP_SCP03_HOSTCRYPTO		\
) > 1)
#error "Enable only one of 'SCP'"
#endif

#if ((0				\
+ SSS_HAVE_SCP_NONE		\
+ SSS_HAVE_SCP_SCP03_SSS	\
+ SSS_HAVE_SCP_SCP03_HOSTCRYPTO	\
) == 0)
#error "Enable at-least one of 'SCP'"
#endif

#define SSS_HAVE_A71CH_AUTH_NONE 1
#define SSS_HAVE_A71CH_AUTH_SCP03 0

#if ((0					\
+ SSS_HAVE_A71CH_AUTH_NONE		\
+ SSS_HAVE_A71CH_AUTH_SCP03		\
) > 1)
#error "Enable only one of 'A71CH_AUTH'"
#endif

#if ((0				\
+ SSS_HAVE_A71CH_AUTH_NONE	\
+ SSS_HAVE_A71CH_AUTH_SCP03	\
) == 0)
#error "Enable at-least one of 'A71CH_AUTH'"
#endif

/* Feature selection/values */
#define SSSFTR_SE05X_AES 1
#define SSSFTR_SE05X_ECC 1
#define SSSFTR_SE05X_RSA 1
#define SSSFTR_SE05X_KEY_SET 1
#define SSSFTR_SE05X_KEY_GET 1
#define SSSFTR_SE05X_AuthECKey 0

#define SSSFTR_SE05X_AuthSession 0
#define SSSFTR_SE05X_CREATE_DELETE_CRYPTOOBJ 1
#define SSSFTR_SW_AES 1
#define SSSFTR_SW_ECC 1
#define SSSFTR_SW_RSA 1
#define SSSFTR_SW_KEY_SET 1
#define SSSFTR_SW_KEY_GET 1
#define SSSFTR_SW_TESTCOUNTERPART 1

/* Computed Options */
#define SSSFTR_AES		(SSSFTR_SE05X_AES + SSSFTR_SW_AES)
#define SSSFTR_ECC		(SSSFTR_SE05X_ECC + SSSFTR_SW_ECC)
#define SSSFTR_RSA		(SSSFTR_SE05X_RSA + SSSFTR_SW_RSA)
#define SSSFTR_KEY_SET		(SSSFTR_SE05X_KEY_SET + SSSFTR_SW_KEY_SET)
#define SSSFTR_KEY_GET		(SSSFTR_SE05X_KEY_GET + SSSFTR_SW_KEY_GET)
#define SSSFTR_KEY		(SSSFTR_KEY_SET + SSSFTR_KEY_GET)
#define SSSFTR_SE05X_KEY	(SSSFTR_SE05X_KEY_SET + SSSFTR_SE05X_KEY_GET)
#define SSSFTR_SW_KEY		(SSSFTR_SW_KEY_SET + SSSFTR_SW_KEY_GET)

#define SSS_HAVE_APPLET					\
(SSS_HAVE_APPLET_A71CH | SSS_HAVE_APPLET_A71CL |	\
SSS_HAVE_APPLET_A71CH_SIM | SSS_HAVE_APPLET_SE05X_A |	\
SSS_HAVE_APPLET_SE05X_B | SSS_HAVE_APPLET_SE05X_C |	\
SSS_HAVE_APPLET_SE05X_L | SSS_HAVE_APPLET_LOOPBACK)

#define SSS_HAVE_APPLET_SE05X_IOT			\
(SSS_HAVE_APPLET_SE05X_A | SSS_HAVE_APPLET_SE05X_B |	\
SSS_HAVE_APPLET_SE05X_C)

#define SSS_HAVE_MBEDTLS_ALT				\
(SSS_HAVE_MBEDTLS_ALT_SSS | SSS_HAVE_MBEDTLS_ALT_A71CH)

#define SSS_HAVE_HOSTCRYPTO_ANY				\
(SSS_HAVE_HOSTCRYPTO_MBEDTLS | SSS_HAVE_HOSTCRYPTO_MBEDCRYPTO |	\
SSS_HAVE_HOSTCRYPTO_OPENSSL | SSS_HAVE_HOSTCRYPTO_USER)

#if SSS_HAVE_APPLET_SE05X_IOT

#if SSS_HAVE_SE05X_VER_04_12
#define SSS_HAVE_SE05X_VER_GTE_04_12 1
#define SSS_HAVE_SE05X_VER_GTE_04_08 1
#define SSS_HAVE_SE05X_VER_GTE_04_04 1
#define SSS_HAVE_SE05X_VER_GTE_03_XX 1
#endif /* SSS_HAVE_SE05X_VER_04_12 */

#if SSS_HAVE_SE05X_VER_04_08
#define SSS_HAVE_SE05X_VER_GTE_04_12 0
#define SSS_HAVE_SE05X_VER_GTE_04_08 1
#define SSS_HAVE_SE05X_VER_GTE_04_04 1
#define SSS_HAVE_SE05X_VER_GTE_03_XX 1
#endif /* SSS_HAVE_SE05X_VER_04_08 */

#if SSS_HAVE_SE05X_VER_04_04
#define SSS_HAVE_SE05X_VER_GTE_04_12 0
#define SSS_HAVE_SE05X_VER_GTE_04_08 0
#define SSS_HAVE_SE05X_VER_GTE_04_04 1
#define SSS_HAVE_SE05X_VER_GTE_03_XX 1
#endif /* SSS_HAVE_SE05X_VER_04_04 */

#if SSS_HAVE_SE05X_VER_03_XX
#define SSS_HAVE_SE05X_VER_GTE_04_12 0
#define SSS_HAVE_SE05X_VER_GTE_04_08 0
#define SSS_HAVE_SE05X_VER_GTE_04_04 0
#define SSS_HAVE_SE05X_VER_GTE_03_XX 1
#endif /* SSS_HAVE_SE05X_VER_03_XX */

#else //SSS_HAVE_APPLET_SE05X_IOT
#define SSS_HAVE_SE05X_VER_GTE_03_XX 0
#define SSS_HAVE_SE05X_VER_GTE_04_04 0
#define SSS_HAVE_SE05X_VER_GTE_04_08 0
#define SSS_HAVE_SE05X_VER_GTE_04_12 0
#endif // SSS_HAVE_APPLET_SE05X_IOT

/* Deprecated items. Used here for backwards compatibility. */
#define WithApplet_SE05X (SSS_HAVE_APPLET_SE05X_IOT)
#define WithApplet_SE050_A (SSS_HAVE_APPLET_SE05X_A)
#define WithApplet_SE050_B (SSS_HAVE_APPLET_SE05X_B)
#define WithApplet_SE050_C (SSS_HAVE_APPLET_SE05X_C)
#define SSS_HAVE_SE050_A (SSS_HAVE_APPLET_SE05X_A)
#define SSS_HAVE_SE050_B (SSS_HAVE_APPLET_SE05X_B)
#define SSS_HAVE_SE050_C (SSS_HAVE_APPLET_SE05X_C)
#define SSS_HAVE_SE05X (SSS_HAVE_APPLET_SE05X_IOT)
#define SSS_HAVE_SE (SSS_HAVE_APPLET)
#define SSS_HAVE_LOOPBACK (SSS_HAVE_APPLET_LOOPBACK)
#define SSS_HAVE_ALT (SSS_HAVE_MBEDTLS_ALT)
#define WithApplet_None (SSS_HAVE_APPLET_NONE)
#define SSS_HAVE_None (SSS_HAVE_APPLET_NONE)
#define WithApplet_A71CH (SSS_HAVE_APPLET_A71CH)
#define SSS_HAVE_A71CH (SSS_HAVE_APPLET_A71CH)
#define WithApplet_A71CL (SSS_HAVE_APPLET_A71CL)
#define SSS_HAVE_A71CL (SSS_HAVE_APPLET_A71CL)
#define WithApplet_A71CH_SIM (SSS_HAVE_APPLET_A71CH_SIM)
#define SSS_HAVE_A71CH_SIM (SSS_HAVE_APPLET_A71CH_SIM)
#define WithApplet_SE05X_A (SSS_HAVE_APPLET_SE05X_A)
#define SSS_HAVE_SE05X_A (SSS_HAVE_APPLET_SE05X_A)
#define WithApplet_SE05X_B (SSS_HAVE_APPLET_SE05X_B)
#define SSS_HAVE_SE05X_B (SSS_HAVE_APPLET_SE05X_B)
#define WithApplet_SE05X_C (SSS_HAVE_APPLET_SE05X_C)
#define SSS_HAVE_SE05X_C (SSS_HAVE_APPLET_SE05X_C)
#define WithApplet_SE05X_L (SSS_HAVE_APPLET_SE05X_L)
#define SSS_HAVE_SE05X_L (SSS_HAVE_APPLET_SE05X_L)
#define WithApplet_LoopBack (SSS_HAVE_APPLET_LOOPBACK)
#define SSS_HAVE_LoopBack (SSS_HAVE_APPLET_LOOPBACK)
#define SSS_HAVE_MBEDTLS (SSS_HAVE_HOSTCRYPTO_MBEDTLS)
#define SSS_HAVE_MBEDCRYPTO (SSS_HAVE_HOSTCRYPTO_MBEDCRYPTO)
#define SSS_HAVE_OPENSSL (SSS_HAVE_HOSTCRYPTO_OPENSSL)
#define SSS_HAVE_USER (SSS_HAVE_HOSTCRYPTO_USER)
#define SSS_HAVE_NONE (SSS_HAVE_HOSTCRYPTO_NONE)
#define SSS_HAVE_ALT_SSS (SSS_HAVE_MBEDTLS_ALT_SSS)
#define SSS_HAVE_ALT_A71CH (SSS_HAVE_MBEDTLS_ALT_A71CH)
#define SSS_HAVE_ALT_NONE (SSS_HAVE_MBEDTLS_ALT_NONE)
#define SSS_HAVE_SE05X_Auth_None (SSS_HAVE_SE05X_AUTH_NONE)
#define SSS_HAVE_SE05X_Auth_UserID (SSS_HAVE_SE05X_AUTH_USERID)
#define SSS_HAVE_SE05X_Auth_PlatfSCP03 (SSS_HAVE_SE05X_AUTH_PLATFSCP03)
#define SSS_HAVE_SE05X_Auth_AESKey (SSS_HAVE_SE05X_AUTH_AESKEY)
#define SSS_HAVE_SE05X_Auth_ECKey (SSS_HAVE_SE05X_AUTH_ECKEY)
#define SSS_HAVE_SE05X_Auth_UserID_PlatfSCP03 \
(SSS_HAVE_SE05X_AUTH_USERID_PLATFSCP03)
#define SSS_HAVE_SE05X_Auth_AESKey_PlatfSCP03 \
(SSS_HAVE_SE05X_AUTH_AESKEY_PLATFSCP03)
#define SSS_HAVE_SE05X_Auth_ECKey_PlatfSCP03 \
(SSS_HAVE_SE05X_AUTH_ECKEY_PLATFSCP03)

/* Miscellaneous values */
#define SSS_HAVE_FIPS 0
#define SSS_HAVE_ECC 1
#define SSS_HAVE_RSA 1
#define SSS_HAVE_TPM_BN 1
#define SSS_HAVE_EC_ED 1
#define SSS_HAVE_EC_MONT 1
#define SSS_HAVE_TLS_HANDSHAKE 1
#define SSS_HAVE_IMPORT 1
#define SSS_HAVE_NXPNFCRDLIB 0

#define SSS_HAVE_A71XX				\
(SSS_HAVE_APPLET_A71CH | SSS_HAVE_APPLET_A71CH_SIM)

#define SSS_HAVE_SSCP  (SSS_HAVE_A71XX)
#define SSS_HAVE_TESTCOUNTERPART (SSSFTR_SW_TESTCOUNTERPART)

/* Calculated values  */
#define SSS_HAVE_SSS (0				\
+ SSS_HAVE_SSCP					\
+ SSS_HAVE_APPLET_SE05X_IOT			\
+ SSS_HAVE_HOSTCRYPTO_OPENSSL			\
+ SSS_HAVE_HOSTCRYPTO_MBEDCRYPTO		\
+ SSS_HAVE_HOSTCRYPTO_MBEDTLS			\
+ SSS_HAVE_HOSTCRYPTO_USER			\
)

#if SSS_HAVE_HOSTCRYPTO_MBEDCRYPTO
#undef SSS_HAVE_MBEDTLS
#undef SSS_HAVE_HOSTCRYPTO_MBEDTLS
#define SSS_HAVE_MBEDTLS 1
#define SSS_HAVE_HOSTCRYPTO_MBEDTLS 1
#endif

#if SSS_HAVE_HOSTCRYPTO_NONE
#undef SSSFTR_SE05X_AuthSession
#define SSSFTR_SE05X_AuthSession 0
#endif

#endif /* SSS_APIS_INC_FSL_SSS_FTR_H_ */
