/* SPDX-License-Identifier: BSD-3-Clause */
/*
 * Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
 */

#ifndef RAMBLUR_PIMEM_HWIO_H
#define RAMBLUR_PIMEM_HWIO_H

#include <stddef.h>

#define RAMBLUR_PIMEM_REG_SIZE 0x4000

/*
 * RAMBLUR_PIMEM_ESR: Error Status Register
 *
 * [bit] [type of error]
 * 12    PIMEM_KERNEL_RACE_CONDITION          Read
 * 11    DDR_BUS_ERROR_FOR_DELAYED_FLUSH      Read/Write
 * 10    L0_VAULT_TRANSACTION_ERROR           Read/Write
 * 9     L1_VAULT_TRANSACTION_ERROR           Read/Write
 * 8     L2_VAULT_TRANSACTION_ERROR           Read/Write
 * 7     PK_VAULT_TRANSACTION_ERROR           Read/Write
 * 6     DATA_AUTH_ERROR                      Read
 * 5     L0_AUTH_ERROR                        Read
 * 4     L1_AUTH_ERROR                        Read
 * 3     L2_AUTH_ERROR                        Read
 * 2     PIMEM_DISABLED_ERROR                 Read/Write
 * 1     CLIENT_ADDR_DECODE_ERROR             Read/Write
 * 0     CFG_ADDR_DECODE_ERROR                Read/Write
 */

#define RAMBLUR_PIMEM_ESR_RMSK			0x1ff
#define RAMBLUR_PIMEM_ESR_ADDR_OFFSET		0x00000110
#define RAMBLUR_PIMEM_ESR_ADDR			\
	(RAMBLUR_PIMEM_ESR_ADDR_OFFSET)

/*
 * Syndrome Registers: when the pIMEM hardware detects an error,
 * information about the error is captured in:
 *
 *	RAMBLUR_PIMEM_ESR
 *	RAMBLUR_PIMEM_ESYNR0
 *	RAMBLUR_PIMEM_ESYNR1
 *
 * RAMBLUR_PIMEM_ESYNR0 and RAMBLUR_PIMEM_ESYNR1 capture information
 * about the QSB transaction on the pIMEM slave that resulted in the
 * error.
 */

#define RAMBLUR_PIMEM_EAR0_RMSK			0xffffffff
#define RAMBLUR_PIMEM_EAR0_ADDR_OFFSET		0x00000114
#define RAMBLUR_PIMEM_EAR0_ADDR			\
	(RAMBLUR_PIMEM_EAR0_ADDR_OFFSET)

#define RAMBLUR_PIMEM_EAR1_RMSK			0xffffffff
#define RAMBLUR_PIMEM_EAR1_ADDR_OFFSET		0x00000118
#define RAMBLUR_PIMEM_EAR1_ADDR			\
	(RAMBLUR_PIMEM_EAR1_ADDR_OFFSET)

#define RAMBLUR_PIMEM_ESYNR0_RMSK		0xffffffff
#define RAMBLUR_PIMEM_ESYNR0_ADDR_OFFSET	0x0000011c
#define RAMBLUR_PIMEM_ESYNR0_ADDR		\
	(RAMBLUR_PIMEM_ESYNR0_ADDR_OFFSET)

#define RAMBLUR_PIMEM_ESYNR1_RMSK		0x3fffffff
#define RAMBLUR_PIMEM_ESYNR1_ADDR_OFFSET	0x00000120
#define RAMBLUR_PIMEM_ESYNR1_ADDR		\
	(RAMBLUR_PIMEM_ESYNR1_ADDR_OFFSET)

/*
 * RAMBLUR_PIMEM_VERSION: PIMEM Version Details
 *
 * [bits]  [value]
 * 31:24   MAJOR_VERSION
 * 23:16   MINOR_VERSION
 * 15:0    STEP_VERSION
 */

#define RAMBLUR_PIMEM_VERSION_MAJOR_VERSION_BMSK	0xff000000
#define RAMBLUR_PIMEM_VERSION_MINOR_VERSION_BMSK	0x00ff0000
#define RAMBLUR_PIMEM_VERSION_STEP_VERSION_BMSK		0x0000ffff
#define RAMBLUR_PIMEM_VERSION_MAJOR_VERSION_SHFT	0x18
#define RAMBLUR_PIMEM_VERSION_MINOR_VERSION_SHFT	0x10
#define RAMBLUR_PIMEM_VERSION_STEP_VERSION_SHFT		0x0
#define RAMBLUR_PIMEM_VERSION_ADDR_OFFSET		0x00000000
#define RAMBLUR_PIMEM_VERSION_ADDR			\
	(RAMBLUR_PIMEM_VERSION_ADDR_OFFSET)

/*
 * RAMBLUR_PIMEM_STATUS: Holds the current status value of PIMEM
 *
 * [bits]  [status]
 * 19      ARC_CACHE_FLUSH_AND_INVALIDATE_IN_PROGRESS
 * 18      ARC_CACHE_FLUSH_ONLY_IN_PROGRESS
 * 17:12   NUM_TXN_IN_FLIGHT
 * 11:6    MASTER_OUTSTANDING
 * 5:0     SLAVE_OUTSTANDING
 */

#define RAMBLUR_PIMEM_STATUS_RMSK		0x000fffff
#define RAMBLUR_PIMEM_STATUS_ADDR_OFFSET	0x00000100
#define RAMBLUR_PIMEM_STATUS_ADDR		\
	(RAMBLUR_PIMEM_STATUS_ADDR_OFFSET)

/*
 * RAMBLUR_PIMEM_WINn_ALGORITHM_CONFIG (n=[0..3]):
 * registers to assign security attributes (algorithms) to PIMEM
 * windows.
 */

#define RAMBLUR_PIMEM_WINn_ALGORITHM_RMSK			0x7
#define RAMBLUR_PIMEM_WINn_ALGORITHM_CONFIG_ADDR_OFFSET(n)	\
	(0x00000068 + (0x4 * (n)))
#define RAMBLUR_PIMEM_WINn_ALGORITHM_CONFIG_ADDR(n)		\
	(RAMBLUR_PIMEM_WINn_ALGORITHM_CONFIG_ADDR_OFFSET(n))

/* Security attributes position in ALGORITHM_CONFIG register */

#define RAMBLUR_PIMEM_WIN0_ALGORITHM_CONFIG_WIN_CONFIDENTIALITY_ENABLE_SHFT \
	0x2
#define RAMBLUR_PIMEM_WIN0_ALGORITHM_CONFIG_WIN_INTEGRITY_ENABLE_SHFT \
	0x1
#define RAMBLUR_PIMEM_WIN0_ALGORITHM_CONFIG_WIN_ANTIROLLBACK_ENABLE_SHFT \
	0x0

/*
 * RAMBLUR_PIMEM_WINn_SIZE (n=[0..3]): registers to set window size
 *
 * [bits]  [value]
 * 26:20   WIN_SIZE
 */

#define RAMBLUR_PIMEM_WINn_SIZE_RMSK			0x07f00000
#define RAMBLUR_PIMEM_WINn_SIZE_ADDR_OFFSET(n)		\
	(0x00000058 + 0x4 * (n))
#define RAMBLUR_PIMEM_WINn_SIZE_ADDR(n)			\
	(RAMBLUR_PIMEM_WINn_SIZE_ADDR_OFFSET(n))

/*
 * RAMBLUR_PIMEM_ADV_CTL: PIMEM Advance Control Register
 *
 * Bits    Field Name
 * 20      DISABLE_ON_AUTH_ERROR
 * 3:0     AHB2AHB_BRIDGE_HYSTERESIS_VALUE
 */

#define RAMBLUR_PIMEM_ADV_CTL_RMSK			0xffffffff
#define RAMBLUR_PIMEM_ADV_CTL_ADDR_OFFSET		0x0000010c
#define RAMBLUR_PIMEM_ADV_CTL_ADDR			\
	(RAMBLUR_PIMEM_ADV_CTL_ADDR_OFFSET)
#define RAMBLUR_PIMEM_ADV_CTL_IN			\
	in_dword_masked(RAMBLUR_PIMEM_ADV_CTL_ADDR,	\
			RAMBLUR_PIMEM_ADV_CTL_RMSK)

#define RAMBLUR_PIMEM_ADV_CTL_DISABLE_ON_AUTH_ERROR_BMSK	0x00100000
#define DISABLE_ON_AUTH_ERROR_BMSK				\
	RAMBLUR_PIMEM_ADV_CTL_DISABLE_ON_AUTH_ERROR_BMSK
#define RAMBLUR_PIMEM_ADV_CTL_DISABLE_ON_AUTH_ERROR_SHIFT	0x14
#define DISABLE_ON_AUTH_ERROR_SHIFT				\
	RAMBLUR_PIMEM_ADV_CTL_DISABLE_ON_AUTH_ERROR_SHIFT

/*
 * RAMBLUR_PIMEM_WINn_CTL, n=[0..3]
 *
 * Bits  Name
 * 3     START_HW_INIT
 * 2     SW_INIT_MODE
 * 1     WIN_ENABLE_REQ
 * 0     WIN_DISABLE_REQ
 */

#define RAMBLUR_PIMEM_WINn_CTL_OFFSET(n)		\
	(0x00000078 + (0x4 * (n)))
#define RAMBLUR_PIMEM_WINn_CTL_ADDR(n)			\
	(RAMBLUR_PIMEM_WINn_CTL_OFFSET(n))
#define RAMBLUR_PIMEM_WINn_CTL_RMSK			0x0000000f
#define RAMBLUR_PIMEM_WINn_CTL_START_HW_INIT_BMSK	0x8
#define RAMBLUR_PIMEM_WINn_CTL_START_HW_INIT_SHFT	0x3
#define RAMBLUR_PIMEM_WINn_CTL_SW_INIT_MODE_BMSK	0x4
#define RAMBLUR_PIMEM_WINn_CTL_SW_INIT_MODE_SHFT	0x2
#define RAMBLUR_PIMEM_WINn_CTL_WIN_ENABLE_REQ_BMSK	0x2
#define RAMBLUR_PIMEM_WINn_CTL_WIN_ENABLE_REQ_SHFT	0x1
#define RAMBLUR_PIMEM_WINn_CTL_WIN_DISABLE_REQ_BMSK	0x1
#define RAMBLUR_PIMEM_WINn_CTL_WIN_DISABLE_REQ_SHFT	0x0

#define RAMBLUR_PIMEM_WINn_CTL_INI(n)			\
	in_dword_masked(RAMBLUR_PIMEM_WINn_CTL_ADDR(n),	\
			RAMBLUR_PIMEM_WINn_CTL_RMSK)

/*
 * RAMBLUR_PIMEM_WINn_STATUS, n=[0..3]
 *
 * Bits  Name
 * 2     HW_INIT_DONE
 * 1     HW_INIT_IN_PROGRESS
 * 0     WIN_ENABLE_STATUS
 */

#define RAMBLUR_PIMEM_WINn_STATUS_OFFSET(n)		\
	(0x00000098 + (0x4 * (n)))
#define RAMBLUR_PIMEM_WINn_STATUS_ADDR(n)		\
	(RAMBLUR_PIMEM_WINn_STATUS_OFFSET(n))
#define RAMBLUR_PIMEM_WINn_STATUS_RMSK			0x3

#define RAMBLUR_PIMEM_WINn_STATUS_INI(n)			\
	in_dword_masked(RAMBLUR_PIMEM_WINn_STATUS_ADDR(n),	\
			RAMBLUR_PIMEM_WINn_STATUS_RMSK)

#define RAMBLUR_PIMEM_WINn_STATUS_HW_INIT_DONE_BMSK		0x4
#define RAMBLUR_PIMEM_WINn_STATUS_HW_INIT_DONE_SHFT		0x2
#define RAMBLUR_PIMEM_WINn_STATUS_HW_INIT_IN_PROGRESS_BMSK	0x2
#define RAMBLUR_PIMEM_WINn_STATUS_HW_INIT_IN_PROGRESS_SHFT	0x1
#define RAMBLUR_PIMEM_WINn_STATUS_WIN_ENABLE_STATUS_BMSK	0x1
#define RAMBLUR_PIMEM_WINn_STATUS_WIN_ENABLE_STATUS_SHFT	0x0

/*
 * RAMBLUR_PIMEM_WINn_HW_INIT_START_OFFSET, n=[0..3]
 *
 * Bits  Name
 * 25:15 INIT_START_OFFSET
 */

#define RAMBLUR_PIMEM_WINn_HW_INIT_START_OFFSET_OFFSET(n)	\
	(0x00000088 + (0x4 * (n)))
#define RAMBLUR_PIMEM_WINn_HW_INIT_START_OFFSET_ADDR(n)		\
	(RAMBLUR_PIMEM_WINn_HW_INIT_START_OFFSET_OFFSET(n))
#define RAMBLUR_PIMEM_WINn_HW_INIT_START_OFFSET_RMSK		0x3ff8000U
#define RAMBLUR_PIMEM_WINn_HW_INIT_START_OFFSET_INIT_START_OFFSET_BMSK \
	0x3ff8000U
#define RAMBLUR_PIMEM_WINn_HW_INIT_START_OFFSET_INIT_START_OFFSET_SHFT \
	0xfU

#define RAMBLUR_PIMEM_WINn_HW_INIT_START_OFFSET_INI(n)		\
	in_dword_masked(					\
		RAMBLUR_PIMEM_WINn_HW_INIT_START_OFFSET_ADDR(n), \
		RAMBLUR_PIMEM_WINn_HW_INIT_START_OFFSET_RMSK)

/*
 * RAMBLUR_PIMEM_WINn_DATA_VAULT_START_ADDR_HI, n=[0..3]
 *
 * Bits  Field Name
 * 3:0   DATA_VAULT_START_ADDR_HI
 *
 * RAMBLUR_PIMEM_WINn_DATA_VAULT_START_ADDR_LOW, n=[0..3]
 * Bits  Field Name
 * 31:20 DATA_VAULT_START_ADDR_LOW
 */

#define RAMBLUR_PIMEM_WINn_DATA_VAULT_START_ADDR_HI_RMSK	0xf
#define RAMBLUR_PIMEM_WINn_DATA_VAULT_START_ADDR_HI_OFFSET(n)	\
	(0x00000038 + (0x4 * (n)))
#define RAMBLUR_PIMEM_WINn_DATA_VAULT_START_ADDR_HI_ADDR(n)	\
	(RAMBLUR_PIMEM_WINn_DATA_VAULT_START_ADDR_HI_OFFSET(n))

#define RAMBLUR_PIMEM_WINn_DATA_VAULT_START_ADDR_LOW_RMSK	0xfff00000
#define RAMBLUR_PIMEM_WINn_DATA_VAULT_START_ADDR_LOW_OFFSET(n) \
	(0x00000048 + (0x4 * (n)))
#define RAMBLUR_PIMEM_WINn_DATA_VAULT_START_ADDR_LOW_ADDR(n)	\
	(RAMBLUR_PIMEM_WINn_DATA_VAULT_START_ADDR_LOW_OFFSET(n))

/* RAMBLUR_PIMEM_OVERHEAD_VAULT start and end addresses */

#define RAMBLUR_PIMEM_OVERHEAD_VAULT_START_ADDR_HI_OFFSET	0x00000028
#define RAMBLUR_PIMEM_OVERHEAD_VAULT_START_ADDR_HI_ADDR		\
	(RAMBLUR_PIMEM_OVERHEAD_VAULT_START_ADDR_HI_OFFSET)
#define RAMBLUR_PIMEM_OVERHEAD_VAULT_START_ADDR_HI_RMSK	0xf

#define RAMBLUR_PIMEM_OVERHEAD_VAULT_START_ADDR_LOW_OFFSET	0x0000002c
#define RAMBLUR_PIMEM_OVERHEAD_VAULT_START_ADDR_LOW_ADDR	\
	(RAMBLUR_PIMEM_OVERHEAD_VAULT_START_ADDR_LOW_OFFSET)
#define RAMBLUR_PIMEM_OVERHEAD_VAULT_START_ADDR_LOW_RMSK	0xfff00000

#define RAMBLUR_PIMEM_OVERHEAD_VAULT_END_ADDR_HI_OFFSET		0x00000030
#define RAMBLUR_PIMEM_OVERHEAD_VAULT_END_ADDR_HI_ADDR		\
	(RAMBLUR_PIMEM_OVERHEAD_VAULT_END_ADDR_HI_OFFSET)
#define RAMBLUR_PIMEM_OVERHEAD_VAULT_END_ADDR_HI_RMSK		0xf

#define RAMBLUR_PIMEM_OVERHEAD_VAULT_END_ADDR_LOW_OFFSET	0x00000034
#define RAMBLUR_PIMEM_OVERHEAD_VAULT_END_ADDR_LOW_ADDR		\
	(RAMBLUR_PIMEM_OVERHEAD_VAULT_END_ADDR_LOW_OFFSET)
#define RAMBLUR_PIMEM_OVERHEAD_VAULT_END_ADDR_LOW_RMSK		0xffffffff

/*
 * RAMBLUR_PIMEM_WINn_DATA_TXN_QSB_CTL, n=[0..3]
 *
 * Bits  Name
 * 27:23 ASCID
 * 22    ACGRANULETRANS
 * 21:18 ACACHEOPTYPE
 * 17    PROTNS
 * 16    AWRITETHROUGH
 * 15    ACACHEABLE
 * 14    AINNERCACHEABLE
 * 13    ANOALLOCATE
 * 12:11 PRIORITYLVL
 * 10:9  AREQPRIORITY
 * 8     ADEVICE
 * 7     ADEVICETYPE
 * 6     ASHARED
 * 5     AINNERSHARED
 * 4     APRIV
 * 3     AOOORD
 * 2     AOOOWR
 * 1     AREDIRECT
 * 0     ATRANSIENT
 */

#define RAMBLUR_PIMEM_WINn_DATA_TXN_QSB_CTL_OFFSET(n)		\
	(0x000000a8 + (0x4 * (n)))
#define RAMBLUR_PIMEM_WINn_DATA_TXN_QSB_CTL_ADDR(n)		\
	(RAMBLUR_PIMEM_WINn_DATA_TXN_QSB_CTL_OFFSET(n))
#define RAMBLUR_PIMEM_WINn_DATA_TXN_QSB_CTL_RMSK		0x0fffffff

#define RAMBLUR_PIMEM_WINn_DATA_TXN_QSB_CTL_ASCID_BMSK		0x0f800000
#define RAMBLUR_PIMEM_WINn_DATA_TXN_QSB_CTL_ASCID_SHFT		0x17
#define RAMBLUR_PIMEM_WINn_DATA_TXN_QSB_CTL_ACGRANULETRANS_BMSK \
	0x00400000
#define RAMBLUR_PIMEM_WINn_DATA_TXN_QSB_CTL_ACGRANULETRANS_SHFT \
	0x16
#define RAMBLUR_PIMEM_WINn_DATA_TXN_QSB_CTL_ACACHEOPTYPE_BMSK	0x003c0000
#define RAMBLUR_PIMEM_WINn_DATA_TXN_QSB_CTL_ACACHEOPTYPE_SHFT	0x12
#define RAMBLUR_PIMEM_WINn_DATA_TXN_QSB_CTL_PROTNS_BMSK		0x00020000
#define RAMBLUR_PIMEM_WINn_DATA_TXN_QSB_CTL_PROTNS_SHFT		0x11
#define RAMBLUR_PIMEM_WINn_DATA_TXN_QSB_CTL_AWRITETHROUGH_BMSK	0x00010000
#define RAMBLUR_PIMEM_WINn_DATA_TXN_QSB_CTL_AWRITETHROUGH_SHFT	0x10
#define RAMBLUR_PIMEM_WINn_DATA_TXN_QSB_CTL_ACACHEABLE_BMSK	0x00008000
#define RAMBLUR_PIMEM_WINn_DATA_TXN_QSB_CTL_ACACHEABLE_SHFT	0xf
#define RAMBLUR_PIMEM_WINn_DATA_TXN_QSB_CTL_AINNERCACHEABLE_BMSK \
	0x00004000
#define RAMBLUR_PIMEM_WINn_DATA_TXN_QSB_CTL_AINNERCACHEABLE_SHFT \
	0xe
#define RAMBLUR_PIMEM_WINn_DATA_TXN_QSB_CTL_ANOALLOCATE_BMSK	0x00002000
#define RAMBLUR_PIMEM_WINn_DATA_TXN_QSB_CTL_ANOALLOCATE_SHFT	0xd
#define RAMBLUR_PIMEM_WINn_DATA_TXN_QSB_CTL_PRIORITYLVL_BMSK	0x00001800
#define RAMBLUR_PIMEM_WINn_DATA_TXN_QSB_CTL_PRIORITYLVL_SHFT	0xb
#define RAMBLUR_PIMEM_WINn_DATA_TXN_QSB_CTL_AREQPRIORITY_BMSK	0x00000600
#define RAMBLUR_PIMEM_WINn_DATA_TXN_QSB_CTL_AREQPRIORITY_SHFT	0x9
#define RAMBLUR_PIMEM_WINn_DATA_TXN_QSB_CTL_ADEVICE_BMSK	0x00000100
#define RAMBLUR_PIMEM_WINn_DATA_TXN_QSB_CTL_ADEVICE_SHFT	0x8
#define RAMBLUR_PIMEM_WINn_DATA_TXN_QSB_CTL_ADEVICETYPE_BMSK	0x00000080
#define RAMBLUR_PIMEM_WINn_DATA_TXN_QSB_CTL_ADEVICETYPE_SHFT	0x7
#define RAMBLUR_PIMEM_WINn_DATA_TXN_QSB_CTL_ASHARED_BMSK	0x00000040
#define RAMBLUR_PIMEM_WINn_DATA_TXN_QSB_CTL_ASHARED_SHFT	0x6
#define RAMBLUR_PIMEM_WINn_DATA_TXN_QSB_CTL_AINNERSHARED_BMSK	0x00000020
#define RAMBLUR_PIMEM_WINn_DATA_TXN_QSB_CTL_AINNERSHARED_SHFT	0x5
#define RAMBLUR_PIMEM_WINn_DATA_TXN_QSB_CTL_APRIV_BMSK		0x00000010
#define RAMBLUR_PIMEM_WINn_DATA_TXN_QSB_CTL_APRIV_SHFT		0x4
#define RAMBLUR_PIMEM_WINn_DATA_TXN_QSB_CTL_AOOORD_BMSK		0x00000008
#define RAMBLUR_PIMEM_WINn_DATA_TXN_QSB_CTL_AOOORD_SHFT		0x3
#define RAMBLUR_PIMEM_WINn_DATA_TXN_QSB_CTL_AOOOWR_BMSK		0x00000004
#define RAMBLUR_PIMEM_WINn_DATA_TXN_QSB_CTL_AOOOWR_SHFT		0x2
#define RAMBLUR_PIMEM_WINn_DATA_TXN_QSB_CTL_AREDIRECT_BMSK	0x00000002
#define RAMBLUR_PIMEM_WINn_DATA_TXN_QSB_CTL_AREDIRECT_SHFT	0x1
#define RAMBLUR_PIMEM_WINn_DATA_TXN_QSB_CTL_ATRANSIENT_BMSK	0x00000001
#define RAMBLUR_PIMEM_WINn_DATA_TXN_QSB_CTL_ATRANSIENT_SHFT	0x0

#define RAMBLUR_PIMEM_WINn_DATA_TXN_QSB_CTL_INI(n)			\
	in_dword_masked(						\
		RAMBLUR_PIMEM_WINn_DATA_TXN_QSB_CTL_ADDR(n),		\
		RAMBLUR_PIMEM_WINn_DATA_TXN_QSB_CTL_RMSK)

/*
 * RAMBLUR_PIMEM_WINn_OVERHEAD_TXN_QSB_CTL, n=[0..3]
 *
 * Bits	Name
 * 27:23	ASCID
 * 22		ACGRANULETRANS
 * 21:18	ACACHEOPTYPE
 * 17		PROTNS
 * 16		AWRITETHROUGH
 * 15		ACACHEABLE
 * 14		AINNERCACHEABLE
 * 13		ANOALLOCATE
 * 12:11	PRIORITYLVL
 * 10:09	AREQPRIORITY
 * 8		ADEVICE
 * 7		ADEVICETYPE
 * 6		ASHARED
 * 5		AINNERSHARED
 * 4		APRIV
 * 3		AOOORD
 * 2		AOOOWR
 * 1		AREDIRECT
 * 0		ATRANSIENT
 */

#define RAMBLUR_PIMEM_WINn_OVERHEAD_TXN_QSB_CTL_OFFSET(n)	\
	(0x000000b8 + (0x4 * (n)))

#define RAMBLUR_PIMEM_WINn_OVERHEAD_TXN_QSB_CTL_ADDR(n)		\
	(RAMBLUR_PIMEM_WINn_OVERHEAD_TXN_QSB_CTL_OFFSET(n))

#define RAMBLUR_PIMEM_WINn_OVERHEAD_TXN_QSB_CTL_RMSK		0x0fffffff
#define RAMBLUR_PIMEM_WINn_OVERHEAD_TXN_QSB_CTL_ASCID_BMSK	0x0f800000
#define RAMBLUR_PIMEM_WINn_OVERHEAD_TXN_QSB_CTL_ASCID_SHFT	0x17
#define RAMBLUR_PIMEM_WINn_OVERHEAD_TXN_QSB_CTL_ACGRANULETRANS_BMSK \
	0x00400000
#define RAMBLUR_PIMEM_WINn_OVERHEAD_TXN_QSB_CTL_ACGRANULETRANS_SHFT \
	0x16
#define RAMBLUR_PIMEM_WINn_OVERHEAD_TXN_QSB_CTL_ACACHEOPTYPE_BMSK \
	0x003c0000
#define RAMBLUR_PIMEM_WINn_OVERHEAD_TXN_QSB_CTL_ACACHEOPTYPE_SHFT \
	0x12
#define RAMBLUR_PIMEM_WINn_OVERHEAD_TXN_QSB_CTL_PROTNS_BMSK	0x00020000
#define RAMBLUR_PIMEM_WINn_OVERHEAD_TXN_QSB_CTL_PROTNS_SHFT	0x11
#define RAMBLUR_PIMEM_WINn_OVERHEAD_TXN_QSB_CTL_AWRITETHROUGH_BMSK \
	0x00010000
#define RAMBLUR_PIMEM_WINn_OVERHEAD_TXN_QSB_CTL_AWRITETHROUGH_SHFT \
	0x10
#define RAMBLUR_PIMEM_WINn_OVERHEAD_TXN_QSB_CTL_ACACHEABLE_BMSK \
	0x00008000
#define RAMBLUR_PIMEM_WINn_OVERHEAD_TXN_QSB_CTL_ACACHEABLE_SHFT \
	0xf
#define RAMBLUR_PIMEM_WINn_OVERHEAD_TXN_QSB_CTL_AINNERCACHEABLE_BMSK \
	0x00004000
#define RAMBLUR_PIMEM_WINn_OVERHEAD_TXN_QSB_CTL_AINNERCACHEABLE_SHFT \
	0xe
#define RAMBLUR_PIMEM_WINn_OVERHEAD_TXN_QSB_CTL_ANOALLOCATE_BMSK \
	0x00002000
#define RAMBLUR_PIMEM_WINn_OVERHEAD_TXN_QSB_CTL_ANOALLOCATE_SHFT \
	0xd
#define RAMBLUR_PIMEM_WINn_OVERHEAD_TXN_QSB_CTL_PRIORITYLVL_BMSK \
	0x00001800
#define RAMBLUR_PIMEM_WINn_OVERHEAD_TXN_QSB_CTL_PRIORITYLVL_SHFT \
	0xb
#define RAMBLUR_PIMEM_WINn_OVERHEAD_TXN_QSB_CTL_AREQPRIORITY_BMSK \
	0x00000600
#define RAMBLUR_PIMEM_WINn_OVERHEAD_TXN_QSB_CTL_AREQPRIORITY_SHFT \
	0x9
#define RAMBLUR_PIMEM_WINn_OVERHEAD_TXN_QSB_CTL_ADEVICE_BMSK	0x00000100
#define RAMBLUR_PIMEM_WINn_OVERHEAD_TXN_QSB_CTL_ADEVICE_SHFT	0x8
#define RAMBLUR_PIMEM_WINn_OVERHEAD_TXN_QSB_CTL_ADEVICETYPE_BMSK \
	0x00000080
#define RAMBLUR_PIMEM_WINn_OVERHEAD_TXN_QSB_CTL_ADEVICETYPE_SHFT \
	0x7
#define RAMBLUR_PIMEM_WINn_OVERHEAD_TXN_QSB_CTL_ASHARED_BMSK	0x00000040
#define RAMBLUR_PIMEM_WINn_OVERHEAD_TXN_QSB_CTL_ASHARED_SHFT	0x6
#define RAMBLUR_PIMEM_WINn_OVERHEAD_TXN_QSB_CTL_AINNERSHARED_BMSK \
	0x00000020
#define RAMBLUR_PIMEM_WINn_OVERHEAD_TXN_QSB_CTL_AINNERSHARED_SHFT \
	0x5
#define RAMBLUR_PIMEM_WINn_OVERHEAD_TXN_QSB_CTL_APRIV_BMSK	0x00000010
#define RAMBLUR_PIMEM_WINn_OVERHEAD_TXN_QSB_CTL_APRIV_SHFT	0x4
#define RAMBLUR_PIMEM_WINn_OVERHEAD_TXN_QSB_CTL_AOOORD_BMSK	0x00000008
#define RAMBLUR_PIMEM_WINn_OVERHEAD_TXN_QSB_CTL_AOOORD_SHFT	0x3
#define RAMBLUR_PIMEM_WINn_OVERHEAD_TXN_QSB_CTL_AOOOWR_BMSK	0x00000004
#define RAMBLUR_PIMEM_WINn_OVERHEAD_TXN_QSB_CTL_AOOOWR_SHFT	0x2
#define RAMBLUR_PIMEM_WINn_OVERHEAD_TXN_QSB_CTL_AREDIRECT_BMSK	0x00000002
#define RAMBLUR_PIMEM_WINn_OVERHEAD_TXN_QSB_CTL_AREDIRECT_SHFT	0x1
#define RAMBLUR_PIMEM_WINn_OVERHEAD_TXN_QSB_CTL_ATRANSIENT_BMSK \
	0x00000001
#define RAMBLUR_PIMEM_WINn_OVERHEAD_TXN_QSB_CTL_ATRANSIENT_SHFT \
	0x0

#define RAMBLUR_PIMEM_WINn_OVERHEAD_TXN_QSB_CTL_INI(n)			\
	in_dword_masked(						\
		RAMBLUR_PIMEM_WINn_OVERHEAD_TXN_QSB_CTL_ADDR(n),	\
		RAMBLUR_PIMEM_WINn_OVERHEAD_TXN_QSB_CTL_RMSK)

#endif
