ifeq ($(CFG_HISILICON_PLAT_ACC),y)

$(call force,CFG_CRYPTO_DRIVER,y)
CFG_CRYPTO_DRIVER_DEBUG ?= 0

$(call force,CFG_CRYPTO_DRV_CIPHER,y,Mandated by CFG_HISILICON_PLAT_ACC)

$(call force,CFG_CRYPTO_DRV_ACIPHER,y,Mandated by CFG_HISILICON_PLAT_ACC)

endif
