#ifndef _include_generated_conf_h_
#define _include_generated_conf_h_
#define CFG_AES_GCM_TABLE_BASED 1
#define CFG_ARM32_core 1
#define CFG_ARM32_ldelf 1
#define CFG_ARM32_ta_arm32 1
/* CFG_ARM64_core is not set */
#define CFG_ATTESTATION_PTA 1
#define CFG_ATTESTATION_PTA_KEY_SIZE 3072
/* CFG_AUTO_MAX_PA_BITS is not set */
#define CFG_BOOT_SECONDARY_REQUEST 1
#define CFG_BUILD_IN_TREE_TA 1
/* CFG_CALLOUT is not set */
#define CFG_CC_OPT_LEVEL "s"
#define CFG_COMPAT_GP10_DES 1
#define CFG_CONSOLE_RUNTIME_LOG_LEVEL 0
/* CFG_CONSOLE_RUNTIME_SET is not set */
#define CFG_CORE_ASLR 1
/* CFG_CORE_ASYNC_NOTIF is not set */
#define CFG_CORE_ASYNC_NOTIF_GIC_INTID 0
/* CFG_CORE_BGET_BESTFIT is not set */
#define CFG_CORE_BIGNUM_MAX_BITS 4096
/* CFG_CORE_BTI is not set */
#define CFG_CORE_CLUSTER_SHIFT 2
/* CFG_CORE_DEBUG_CHECK_STACKS is not set */
/* CFG_CORE_DUMP_OOM is not set */
/* CFG_CORE_DYN_PROTMEM is not set */
#define CFG_CORE_DYN_SHM 1
/* CFG_CORE_HAFNIUM_INTC is not set */
/* CFG_CORE_HAS_GENERIC_TIMER is not set */
#define CFG_CORE_HEAP_SIZE 131072
#define CFG_CORE_HUK_SUBKEY_COMPAT 1
#define CFG_CORE_HUK_SUBKEY_COMPAT_USE_OTP_DIE_ID 1
/* CFG_CORE_IRQ_IS_NATIVE_INTR is not set */
/* CFG_CORE_LARGE_PHYS_ADDR is not set */
#define CFG_CORE_MAX_SYSCALL_RECURSION 4
#define CFG_CORE_MBEDTLS_MPI 1
#define CFG_CORE_NEX_HEAP_SIZE 16384
/* CFG_CORE_PAGE_TAG_AND_IV is not set */
/* CFG_CORE_PAUTH is not set */
/* CFG_CORE_PREALLOC_EL0_TBLS is not set */
#define CFG_CORE_RESERVED_SHM 1
/* CFG_CORE_RODATA_NOEXEC is not set */
#define CFG_CORE_RWDATA_NOEXEC 1
/* CFG_CORE_SANITIZE_KADDRESS is not set */
/* CFG_CORE_SANITIZE_UNDEFINED is not set */
/* CFG_CORE_STACK_PROTECTOR is not set */
/* CFG_CORE_STACK_PROTECTOR_ALL is not set */
#define CFG_CORE_STACK_PROTECTOR_STRONG 1
#define CFG_CORE_THREAD_SHIFT 0
/* CFG_CORE_TPM_EVENT_LOG is not set */
#define CFG_CORE_TZSRAM_EMUL_SIZE 458752
#define CFG_CORE_UNMAP_CORE_AT_EL0 1
/* CFG_CORE_UNSAFE_MODEXP is not set */
/* CFG_CORE_WORKAROUND_ARM_NMFI is not set */
#define CFG_CORE_WORKAROUND_NSITR_CACHE_PRIME 1
#define CFG_CORE_WORKAROUND_SPECTRE_BP 1
#define CFG_CORE_WORKAROUND_SPECTRE_BP_SEC 1
#define CFG_CRYPTO 1
#define CFG_CRYPTOLIB_DIR core/lib/libtomcrypt
#define CFG_CRYPTOLIB_NAME tomcrypt
#define CFG_CRYPTOLIB_NAME_tomcrypt 1
#define CFG_CRYPTO_AES 1
/* CFG_CRYPTO_AES_GCM_FROM_CRYPTOLIB is not set */
#define CFG_CRYPTO_CBC 1
#define CFG_CRYPTO_CBC_MAC 1
#define CFG_CRYPTO_CBC_MAC_BUNDLE_BLOCKS 64
#define CFG_CRYPTO_CCM 1
#define CFG_CRYPTO_CMAC 1
#define CFG_CRYPTO_CONCAT_KDF 1
#define CFG_CRYPTO_CTR 1
#define CFG_CRYPTO_CTS 1
#define CFG_CRYPTO_DES 1
#define CFG_CRYPTO_DH 1
#define CFG_CRYPTO_DSA 1
#define CFG_CRYPTO_ECB 1
#define CFG_CRYPTO_ECC 1
#define CFG_CRYPTO_ED25519 1
#define CFG_CRYPTO_GCM 1
#define CFG_CRYPTO_HKDF 1
#define CFG_CRYPTO_HMAC 1
/* CFG_CRYPTO_HW_PBKDF2 is not set */
#define CFG_CRYPTO_MD5 1
#define CFG_CRYPTO_PBKDF2 1
#define CFG_CRYPTO_RSA 1
#define CFG_CRYPTO_RSASSA_NA1 1
#define CFG_CRYPTO_SHA1 1
#define CFG_CRYPTO_SHA224 1
#define CFG_CRYPTO_SHA256 1
#define CFG_CRYPTO_SHA384 1
#define CFG_CRYPTO_SHA3_224 1
#define CFG_CRYPTO_SHA3_256 1
#define CFG_CRYPTO_SHA3_384 1
#define CFG_CRYPTO_SHA3_512 1
#define CFG_CRYPTO_SHA512 1
#define CFG_CRYPTO_SHA512_256 1
#define CFG_CRYPTO_SHAKE128 1
#define CFG_CRYPTO_SHAKE256 1
/* CFG_CRYPTO_SIZE_OPTIMIZATION is not set */
#define CFG_CRYPTO_SM2_DSA 1
#define CFG_CRYPTO_SM2_KEP 1
#define CFG_CRYPTO_SM2_PKE 1
#define CFG_CRYPTO_SM3 1
#define CFG_CRYPTO_SM4 1
#define CFG_CRYPTO_X25519 1
#define CFG_CRYPTO_XTS 1
#define CFG_DDR_SIZE 0x40000000
#define CFG_DEBUG_INFO 1
#define CFG_DEVICE_ENUM_PTA 1
#define CFG_DRAM_BASE 0x10000000
/* CFG_DRIVERS_CLK is not set */
/* CFG_DRIVERS_CLK_DT is not set */
/* CFG_DRIVERS_CLK_EARLY_PROBE is not set */
/* CFG_DRIVERS_CLK_FIXED is not set */
/* CFG_DRIVERS_CLK_PRINT_TREE is not set */
/* CFG_DRIVERS_DT_RECURSIVE_PROBE is not set */
/* CFG_DRIVERS_GPIO is not set */
/* CFG_DRIVERS_I2C is not set */
/* CFG_DRIVERS_NVMEM is not set */
/* CFG_DRIVERS_PINCTRL is not set */
/* CFG_DRIVERS_REGULATOR is not set */
/* CFG_DRIVERS_REGULATOR_PRINT_TREE is not set */
/* CFG_DRIVERS_REMOTEPROC is not set */
/* CFG_DRIVERS_RSTCTRL is not set */
/* CFG_DRIVERS_RTC is not set */
#define CFG_DT 1
#define CFG_DTB_MAX_SIZE 0x20000
/* CFG_DT_CACHED_NODE_INFO is not set */
/* CFG_DT_DRIVER_EMBEDDED_TEST is not set */
#define CFG_DYN_CONFIG 1
/* CFG_EARLY_TA is not set */
#define CFG_EARLY_TA_COMPRESS 1
/* CFG_EMBED_DTB is not set */
#define CFG_ENABLE_EMBEDDED_TESTS 1
#define CFG_ENABLE_SCTLR_RR 1
#define CFG_ENABLE_SCTLR_Z 1
/* CFG_EXTERNAL_ABORT_PLAT_HANDLER is not set */
#define CFG_EXTERNAL_DT 1
/* CFG_EXTERNAL_DTB_OVERLAY is not set */
#define CFG_FAULT_MITIGATION 1
/* CFG_FFA_CONSOLE is not set */
/* CFG_FTRACE_DUMP_EVERY_ENTRY is not set */
/* CFG_FTRACE_SUPPORT is not set */
/* CFG_GENERATE_DTB_OVERLAY is not set */
#define CFG_GIC 1
#define CFG_GP_SOCKETS 1
/* CFG_HALT_CORES_ON_PANIC is not set */
#define CFG_HALT_CORES_SGI 15
/* CFG_HMAC_64_1024_RANGE is not set */
/* CFG_HWRNG_PTA is not set */
/* CFG_HWSUPP_MEM_PERM_PXN is not set */
/* CFG_HWSUPP_MEM_PERM_WXN is not set */
#define CFG_IMX_CAAM 1
#define CFG_IMX_CSU 1
#define CFG_IMX_DIGPROG 1
#define CFG_IMX_OCOTP 1
#define CFG_IMX_PM 1
#define CFG_IMX_SCU 1
#define CFG_IMX_SNVS 1
#define CFG_IMX_UART 1
#define CFG_IMX_WDOG 1
#define CFG_INSECURE 1
#define CFG_KERN_LINKER_ARCH arm
#define CFG_KERN_LINKER_FORMAT elf32-littlearm
#define CFG_LIBUTILS_WITH_COMPILER_RT 1
#define CFG_LIBUTILS_WITH_ISOC 1
/* CFG_LOCKDEP is not set */
#define CFG_LOCKDEP_RECORD_STACK 1
#define CFG_LPAE_ADDR_SPACE_BITS 32
/* CFG_MAP_EXT_DT_SECURE is not set */
#define CFG_MAX_CACHE_LINE_SHIFT 6
/* CFG_MEMTAG is not set */
#define CFG_MMAP_REGIONS 24
#define CFG_MSG_LONG_PREFIX_MASK 0x1a
/* CFG_MULTI_CORE_HALTING is not set */
#define CFG_MX6 1
#define CFG_MX6Q 1
#define CFG_NEX_DYN_VASPACE_SIZE (1024 * 1024)
/* CFG_NOTIF_TEST_WD is not set */
#define CFG_NS_ENTRY_ADDR 0x12000000
/* CFG_NS_VIRTUALIZATION is not set */
#define CFG_NUM_THREADS 2
/* CFG_NXP_CAAM is not set */
/* CFG_OPTEE_REVISION_EXTRA is not set */
#define CFG_OPTEE_REVISION_MAJOR 4
#define CFG_OPTEE_REVISION_MINOR 9
#define CFG_OS_REV_REPORTS_GIT_SHA1 1
#define CFG_PAGEABLE_ADDR 0
/* CFG_PAN is not set */
#define CFG_PGT_CACHE_ENTRIES 8
#define CFG_PKCS11_TA 1
#define CFG_PKCS11_TA_ALLOW_DIGEST_KEY 1
#define CFG_PKCS11_TA_AUTH_TEE_IDENTITY 1
#define CFG_PKCS11_TA_CHECK_VALUE_ATTRIBUTE 1
#define CFG_PKCS11_TA_HEAP_SIZE (32 * 1024)
/* CFG_PKCS11_TA_RSA_X_509 is not set */
#define CFG_PKCS11_TA_TOKEN_COUNT 3
#define CFG_PL310 1
#define CFG_PL310_LOCKED 1
#define CFG_PM_ARM32 1
#define CFG_PREALLOC_RPC_CACHE 1
#define CFG_PSCI_ARM32 1
#define CFG_REE_FS 1
/* CFG_REE_FS_ALLOW_RESET is not set */
#define CFG_REE_FS_HTREE_HASH_SIZE_COMPAT 1
#define CFG_REE_FS_TA 1
/* CFG_REE_FS_TA_BUFFERED is not set */
/* CFG_REGULATOR_FIXED is not set */
/* CFG_REGULATOR_GPIO is not set */
/* CFG_REMOTEPROC_PTA is not set */
#define CFG_REMOTEPROC_TA_HEAP_SIZE (4 * 1024)
#define CFG_RESERVED_VASPACE_SIZE (1024 * 1024 * 10)
/* CFG_RPMB_FS is not set */
/* CFG_RSA_PUB_EXPONENT_3 is not set */
/* CFG_RTC_PTA is not set */
/* CFG_SCMI_MSG_DRIVERS is not set */
/* CFG_SCMI_MSG_USE_CLK is not set */
/* CFG_SCMI_PTA is not set */
/* CFG_SCMI_SCPFW is not set */
/* CFG_SCMI_SCPFW_FROM_DT is not set */
/* CFG_SCTLR_ALIGNMENT_CHECK is not set */
#define CFG_SECSTOR_TA 1
#define CFG_SECSTOR_TA_MGMT_PTA 1
/* CFG_SECURE_DATA_PATH is not set */
/* CFG_SECURE_PARTITION is not set */
/* CFG_SECURE_TIME_SOURCE_CNTPCT is not set */
#define CFG_SECURE_TIME_SOURCE_REE 1
/* CFG_SEMIHOSTING is not set */
/* CFG_SEMIHOSTING_CONSOLE is not set */
#define CFG_SEMIHOSTING_CONSOLE_FILE "optee.log"
#define CFG_SHMEM_SIZE 0x00200000
#define CFG_SHMEM_START ((0x10000000 - 0x01e00000 - 0x00200000 + 0x40000000) + 0x01e00000)
/* CFG_SHOW_CONF_ON_BOOT is not set */
#define CFG_SM_NO_CYCLE_COUNTING 1
/* CFG_SPMC_TESTS is not set */
#define CFG_SP_INIT_INFO_MAX_SIZE 0x1000
#define CFG_STACK_THREAD_EXTRA 0
#define CFG_STACK_TMP_EXTRA 0
/* CFG_SYSCALL_FTRACE is not set */
/* CFG_SYSCALL_WRAPPERS_MCOUNT is not set */
#define CFG_SYSTEM_PTA 1
#define CFG_TA_ASLR 1
#define CFG_TA_ASLR_MAX_OFFSET_PAGES 128
#define CFG_TA_ASLR_MIN_OFFSET_PAGES 0
#define CFG_TA_BGET_TEST 1
#define CFG_TA_BIGNUM_MAX_BITS 2048
/* CFG_TA_BTI is not set */
#define CFG_TA_FLOAT_SUPPORT 1
/* CFG_TA_GPROF_SUPPORT is not set */
#define CFG_TA_LIBGCC 1
#define CFG_TA_MBEDTLS 1
#define CFG_TA_MBEDTLS_MPI 1
#define CFG_TA_MBEDTLS_SELF_TEST 1
/* CFG_TA_MBEDTLS_UNSAFE_MODEXP is not set */
/* CFG_TA_OPTEE_CORE_API_COMPAT_1_1 is not set */
/* CFG_TA_PAUTH is not set */
/* CFG_TA_SANITIZE_UNDEFINED is not set */
/* CFG_TA_STACK_PROTECTOR is not set */
/* CFG_TA_STACK_PROTECTOR_ALL is not set */
#define CFG_TA_STACK_PROTECTOR_STRONG 1
/* CFG_TA_STATS is not set */
#define CFG_TA_STRICT_ANNOTATION_CHECKS 1
#define CFG_TEE_API_VERSION GPD-1.1-dev
#define CFG_TEE_CORE_DEBUG 1
#define CFG_TEE_CORE_EMBED_INTERNAL_TESTS 1
#define CFG_TEE_CORE_LOG_LEVEL 2
/* CFG_TEE_CORE_MALLOC_DEBUG is not set */
#define CFG_TEE_CORE_NB_CORE 4
#define CFG_TEE_CORE_TA_TRACE 1
#define CFG_TEE_DYN_VASPACE_SIZE (1024 * 1024)
#define CFG_TEE_FW_IMPL_VERSION FW_IMPL_UNDEF
#define CFG_TEE_FW_MANUFACTURER FW_MAN_UNDEF
#define CFG_TEE_IMPL_DESCR OPTEE
#define CFG_TEE_MANUFACTURER LINARO
#define CFG_TEE_TA_LOG_LEVEL 1
/* CFG_TEE_TA_MALLOC_DEBUG is not set */
/* CFG_TRANSFER_LIST is not set */
/* CFG_TRANSFER_LIST_TEST is not set */
#define CFG_TZC380 1
#define CFG_TZDRAM_SIZE 0x01e00000
#define CFG_TZDRAM_START (0x10000000 - 0x01e00000 - 0x00200000 + 0x40000000)
#define CFG_UART_BASE UART1_BASE
/* CFG_ULIBS_MCOUNT is not set */
/* CFG_ULIBS_SHARED is not set */
#define CFG_UNWIND 1
/* CFG_VERAISON_ATTESTATION_PTA is not set */
#define CFG_VERAISON_ATTESTATION_PTA_TEST_KEY 1
#define CFG_WARN_DECL_AFTER_STATEMENT 1
/* CFG_WDT is not set */
/* CFG_WDT_SM_HANDLER is not set */
#define CFG_WDT_SM_HANDLER_ID 0x82003D06
/* CFG_WIDEVINE_HUK is not set */
/* CFG_WIDEVINE_PTA is not set */
/* CFG_WITH_LPAE is not set */
/* CFG_WITH_PAGER is not set */
#define CFG_WITH_SOFTWARE_PRNG 1
#define CFG_WITH_STACK_CANARIES 1
/* CFG_WITH_STATS is not set */
/* CFG_WITH_STMM_SP is not set */
#define CFG_WITH_USER_TA 1
#define CFG_WITH_VFP 1
#define PLATFORM_FLAVOR mx6qsabresd
#define PLATFORM_FLAVOR_mx6qsabresd 1
#define PLATFORM_imx 1
/* _CFG_ARM_V3_OR_V4 is not set */
/* _CFG_CORE_ASYNC_NOTIF_DEFAULT_IMPL is not set */
#define _CFG_CORE_LTC_ACIPHER 1
#define _CFG_CORE_LTC_AES 1
/* _CFG_CORE_LTC_AES_ACCEL is not set */
#define _CFG_CORE_LTC_AES_DESC 1
#define _CFG_CORE_LTC_ASN1 1
#define _CFG_CORE_LTC_BIGNUM_MAX_BITS 4096
#define _CFG_CORE_LTC_CBC 1
#define _CFG_CORE_LTC_CBC_MAC 1
#define _CFG_CORE_LTC_CCM 1
/* _CFG_CORE_LTC_CE is not set */
#define _CFG_CORE_LTC_CMAC 1
#define _CFG_CORE_LTC_CTR 1
#define _CFG_CORE_LTC_CTS 1
#define _CFG_CORE_LTC_DES 1
#define _CFG_CORE_LTC_DH 1
#define _CFG_CORE_LTC_DSA 1
#define _CFG_CORE_LTC_EC25519 1
#define _CFG_CORE_LTC_ECB 1
#define _CFG_CORE_LTC_ECC 1
#define _CFG_CORE_LTC_ED25519 1
#define _CFG_CORE_LTC_HASH 1
#define _CFG_CORE_LTC_HMAC 1
/* _CFG_CORE_LTC_HWSUPP_PMULL is not set */
#define _CFG_CORE_LTC_MD5 1
#define _CFG_CORE_LTC_MD5_DESC 1
#define _CFG_CORE_LTC_MPI 1
#define _CFG_CORE_LTC_OPTEE_THREAD 1
/* _CFG_CORE_LTC_PAGER is not set */
#define _CFG_CORE_LTC_RSA 1
#define _CFG_CORE_LTC_SHA1 1
/* _CFG_CORE_LTC_SHA1_ACCEL is not set */
#define _CFG_CORE_LTC_SHA1_DESC 1
#define _CFG_CORE_LTC_SHA224 1
#define _CFG_CORE_LTC_SHA224_DESC 1
#define _CFG_CORE_LTC_SHA256 1
/* _CFG_CORE_LTC_SHA256_ACCEL is not set */
#define _CFG_CORE_LTC_SHA256_DESC 1
#define _CFG_CORE_LTC_SHA384 1
#define _CFG_CORE_LTC_SHA384_DESC 1
#define _CFG_CORE_LTC_SHA3_224 1
#define _CFG_CORE_LTC_SHA3_256 1
#define _CFG_CORE_LTC_SHA3_384 1
#define _CFG_CORE_LTC_SHA3_512 1
/* _CFG_CORE_LTC_SHA3_ACCEL is not set */
#define _CFG_CORE_LTC_SHA3_DESC 1
#define _CFG_CORE_LTC_SHA512 1
#define _CFG_CORE_LTC_SHA512_256 1
/* _CFG_CORE_LTC_SHA512_ACCEL is not set */
#define _CFG_CORE_LTC_SHA512_DESC 1
#define _CFG_CORE_LTC_SHAKE128 1
#define _CFG_CORE_LTC_SHAKE256 1
/* _CFG_CORE_LTC_SIZE_OPTIMIZATION is not set */
#define _CFG_CORE_LTC_SM2_DSA 1
#define _CFG_CORE_LTC_SM2_KEP 1
#define _CFG_CORE_LTC_SM2_PKE 1
#define _CFG_CORE_LTC_VFP 1
#define _CFG_CORE_LTC_X25519 1
#define _CFG_CORE_LTC_XTS 1
#define _CFG_CORE_STACK_PROTECTOR 1
#define _CFG_TA_STACK_PROTECTOR 1
/* _CFG_USE_DTB_OVERLAY is not set */
#define _CFG_WITH_SECURE_STORAGE 1
#endif
