#ifndef _include_generated_conf_h_
#define _include_generated_conf_h_
#define CFG_AES_GCM_TABLE_BASED 1
#define CFG_ARM32_core 1
#define CFG_ARM32_ldelf 1
#define CFG_ARM32_ta_arm32 1
/* CFG_ARM64_core is not set */
/* CFG_ATTESTATION_PTA is not set */
/* CFG_AUTO_MAX_PA_BITS is not set */
#define CFG_BOOT_SECONDARY_REQUEST 1
#define CFG_BUILD_IN_TREE_TA 1
/* CFG_CALLOUT is not set */
#define CFG_CC_OPT_LEVEL "s"
#define CFG_COMPAT_GP10_DES 1
#define CFG_CONSOLE_RUNTIME_LOG_LEVEL 0
/* CFG_CONSOLE_RUNTIME_SET is not set */
/* CFG_CORE_ASLR is not set */
/* CFG_CORE_ASYNC_NOTIF is not set */
#define CFG_CORE_ASYNC_NOTIF_GIC_INTID 0
#define CFG_CORE_BGET_BESTFIT 1
#define CFG_CORE_BIGNUM_MAX_BITS 4096
/* CFG_CORE_BTI is not set */
#define CFG_CORE_CLUSTER_SHIFT 2
/* CFG_CORE_DEBUG_CHECK_STACKS is not set */
/* CFG_CORE_DUMP_OOM is not set */
/* CFG_CORE_DYN_PROTMEM is not set */
#define CFG_CORE_DYN_SHM 1
/* CFG_CORE_HAFNIUM_INTC is not set */
#define CFG_CORE_HAS_GENERIC_TIMER 1
#define CFG_CORE_HEAP_SIZE 65536
#define CFG_CORE_HUK_SUBKEY_COMPAT 1
/* CFG_CORE_HUK_SUBKEY_COMPAT_USE_OTP_DIE_ID is not set */
/* CFG_CORE_IRQ_IS_NATIVE_INTR is not set */
/* CFG_CORE_LARGE_PHYS_ADDR is not set */
#define CFG_CORE_MAX_SYSCALL_RECURSION 4
#define CFG_CORE_MBEDTLS_MPI 1
#define CFG_CORE_NEX_HEAP_SIZE 16384
#define CFG_CORE_PAGE_TAG_AND_IV 1
/* CFG_CORE_PAUTH is not set */
/* CFG_CORE_PREALLOC_EL0_TBLS is not set */
/* CFG_CORE_RESERVED_SHM is not set */
/* CFG_CORE_RODATA_NOEXEC is not set */
#define CFG_CORE_RWDATA_NOEXEC 1
/* CFG_CORE_SANITIZE_KADDRESS is not set */
/* CFG_CORE_SANITIZE_UNDEFINED is not set */
/* CFG_CORE_STACK_PROTECTOR is not set */
/* CFG_CORE_STACK_PROTECTOR_ALL is not set */
#define CFG_CORE_STACK_PROTECTOR_STRONG 1
#define CFG_CORE_THREAD_SHIFT 0
/* CFG_CORE_TPM_EVENT_LOG is not set */
#define CFG_CORE_TZSRAM_EMUL_SIZE 458752
#define CFG_CORE_UNMAP_CORE_AT_EL0 1
/* CFG_CORE_UNSAFE_MODEXP is not set */
/* CFG_CORE_WORKAROUND_ARM_NMFI is not set */
#define CFG_CORE_WORKAROUND_NSITR_CACHE_PRIME 1
#define CFG_CORE_WORKAROUND_SPECTRE_BP 1
#define CFG_CORE_WORKAROUND_SPECTRE_BP_SEC 1
#define CFG_CRYPTO 1
#define CFG_CRYPTOLIB_DIR core/lib/libtomcrypt
#define CFG_CRYPTOLIB_NAME tomcrypt
#define CFG_CRYPTOLIB_NAME_tomcrypt 1
#define CFG_CRYPTO_AES 1
/* CFG_CRYPTO_AES_GCM_FROM_CRYPTOLIB is not set */
#define CFG_CRYPTO_CBC 1
#define CFG_CRYPTO_CBC_MAC 1
#define CFG_CRYPTO_CBC_MAC_BUNDLE_BLOCKS 64
#define CFG_CRYPTO_CCM 1
#define CFG_CRYPTO_CMAC 1
#define CFG_CRYPTO_CONCAT_KDF 1
#define CFG_CRYPTO_CTR 1
#define CFG_CRYPTO_CTS 1
#define CFG_CRYPTO_DES 1
#define CFG_CRYPTO_DH 1
#define CFG_CRYPTO_DRIVER 1
#define CFG_CRYPTO_DRIVER_DEBUG 0
#define CFG_CRYPTO_DRV_HASH 1
#define CFG_CRYPTO_DRV_MAC 1
#define CFG_CRYPTO_DSA 1
#define CFG_CRYPTO_ECB 1
#define CFG_CRYPTO_ECC 1
#define CFG_CRYPTO_ED25519 1
#define CFG_CRYPTO_GCM 1
#define CFG_CRYPTO_HKDF 1
#define CFG_CRYPTO_HMAC 1
/* CFG_CRYPTO_HW_PBKDF2 is not set */
#define CFG_CRYPTO_MD5 1
#define CFG_CRYPTO_PBKDF2 1
#define CFG_CRYPTO_RSA 1
#define CFG_CRYPTO_RSASSA_NA1 1
#define CFG_CRYPTO_SHA1 1
#define CFG_CRYPTO_SHA224 1
#define CFG_CRYPTO_SHA256 1
#define CFG_CRYPTO_SHA384 1
#define CFG_CRYPTO_SHA3_224 1
#define CFG_CRYPTO_SHA3_256 1
#define CFG_CRYPTO_SHA3_384 1
#define CFG_CRYPTO_SHA3_512 1
#define CFG_CRYPTO_SHA512 1
#define CFG_CRYPTO_SHA512_256 1
#define CFG_CRYPTO_SHAKE128 1
#define CFG_CRYPTO_SHAKE256 1
#define CFG_CRYPTO_SIZE_OPTIMIZATION 1
#define CFG_CRYPTO_SM2_DSA 1
#define CFG_CRYPTO_SM2_KEP 1
#define CFG_CRYPTO_SM2_PKE 1
#define CFG_CRYPTO_SM3 1
#define CFG_CRYPTO_SM4 1
#define CFG_CRYPTO_X25519 1
#define CFG_CRYPTO_XTS 1
#define CFG_DEBUG_INFO 1
#define CFG_DEVICE_ENUM_PTA 1
#define CFG_DRAM_BASE 0xc0000000
#define CFG_DRAM_SIZE 0x40000000
#define CFG_DRIVERS_CLK 1
#define CFG_DRIVERS_CLK_DT 1
#define CFG_DRIVERS_CLK_EARLY_PROBE 1
/* CFG_DRIVERS_CLK_FIXED is not set */
/* CFG_DRIVERS_CLK_PRINT_TREE is not set */
/* CFG_DRIVERS_DT_RECURSIVE_PROBE is not set */
#define CFG_DRIVERS_FIREWALL 1
#define CFG_DRIVERS_GPIO 1
#define CFG_DRIVERS_I2C 1
/* CFG_DRIVERS_NVMEM is not set */
#define CFG_DRIVERS_PINCTRL 1
#define CFG_DRIVERS_REGULATOR 1
/* CFG_DRIVERS_REGULATOR_PRINT_TREE is not set */
/* CFG_DRIVERS_REMOTEPROC is not set */
#define CFG_DRIVERS_RSTCTRL 1
#define CFG_DRIVERS_RTC 1
#define CFG_DT 1
#define CFG_DTB_MAX_SIZE (256 * 1024)
#define CFG_DT_CACHED_NODE_INFO 1
/* CFG_DT_DRIVER_EMBEDDED_TEST is not set */
/* CFG_DYN_CONFIG is not set */
/* CFG_EARLY_TA is not set */
#define CFG_EARLY_TA_COMPRESS 1
#define CFG_EMBED_DTB 1
#define CFG_EMBED_DTB_SOURCE_FILE stm32mp157a-dhcor-avenger96.dts
#define CFG_ENABLE_EMBEDDED_TESTS 1
/* CFG_ENABLE_SCTLR_Z is not set */
/* CFG_EXTERNAL_ABORT_PLAT_HANDLER is not set */
#define CFG_EXTERNAL_DT 1
/* CFG_EXTERNAL_DTB_OVERLAY is not set */
#define CFG_FAULT_MITIGATION 1
/* CFG_FFA_CONSOLE is not set */
/* CFG_FTRACE_DUMP_EVERY_ENTRY is not set */
/* CFG_FTRACE_SUPPORT is not set */
/* CFG_GENERATE_DTB_OVERLAY is not set */
#define CFG_GIC 1
#define CFG_GP_SOCKETS 1
#define CFG_HALT_CORES_ON_PANIC 1
#define CFG_HALT_CORES_SGI 15
/* CFG_HMAC_64_1024_RANGE is not set */
/* CFG_HWRNG_PTA is not set */
#define CFG_HWSUPP_MEM_PERM_PXN 1
#define CFG_HWSUPP_MEM_PERM_WXN 1
#define CFG_INIT_CNTVOFF 1
#define CFG_INSECURE 1
#define CFG_KERN_LINKER_ARCH arm
#define CFG_KERN_LINKER_FORMAT elf32-littlearm
#define CFG_LIBUTILS_WITH_COMPILER_RT 1
#define CFG_LIBUTILS_WITH_ISOC 1
/* CFG_LOCKDEP is not set */
#define CFG_LOCKDEP_RECORD_STACK 1
#define CFG_LPAE_ADDR_SPACE_BITS 32
/* CFG_MAP_EXT_DT_SECURE is not set */
#define CFG_MAX_CACHE_LINE_SHIFT 6
/* CFG_MEMTAG is not set */
#define CFG_MMAP_REGIONS 23
#define CFG_MSG_LONG_PREFIX_MASK 0x1a
#define CFG_MULTI_CORE_HALTING 1
#define CFG_NEX_DYN_VASPACE_SIZE (1024 * 1024)
/* CFG_NOTIF_TEST_WD is not set */
/* CFG_NS_VIRTUALIZATION is not set */
#define CFG_NUM_THREADS 3
/* CFG_OPTEE_REVISION_EXTRA is not set */
#define CFG_OPTEE_REVISION_MAJOR 4
#define CFG_OPTEE_REVISION_MINOR 9
#define CFG_OS_REV_REPORTS_GIT_SHA1 1
#define CFG_PAGED_USER_TA 1
/* CFG_PAN is not set */
#define CFG_PGT_CACHE_ENTRIES (3 * 2)
#define CFG_PKCS11_TA_ALLOW_DIGEST_KEY 1
#define CFG_PKCS11_TA_AUTH_TEE_IDENTITY 1
#define CFG_PKCS11_TA_CHECK_VALUE_ATTRIBUTE 1
#define CFG_PKCS11_TA_HEAP_SIZE (32 * 1024)
/* CFG_PKCS11_TA_RSA_X_509 is not set */
#define CFG_PKCS11_TA_TOKEN_COUNT 3
/* CFG_PREALLOC_RPC_CACHE is not set */
#define CFG_PSCI_ARM32 1
#define CFG_REE_FS 1
/* CFG_REE_FS_ALLOW_RESET is not set */
#define CFG_REE_FS_HTREE_HASH_SIZE_COMPAT 1
#define CFG_REE_FS_TA 1
/* CFG_REE_FS_TA_BUFFERED is not set */
#define CFG_REGULATOR_FIXED 1
#define CFG_REGULATOR_GPIO 1
/* CFG_REMOTEPROC_PTA is not set */
#define CFG_REMOTEPROC_TA_HEAP_SIZE (4 * 1024)
#define CFG_RESERVED_VASPACE_SIZE (1024 * 1024 * 10)
/* CFG_RPMB_FS is not set */
/* CFG_RSA_PUB_EXPONENT_3 is not set */
#define CFG_RTC_PTA 1
#define CFG_SCMI_MSG_CLOCK 1
#define CFG_SCMI_MSG_DRIVERS 1
/* CFG_SCMI_MSG_PERF_DOMAIN is not set */
#define CFG_SCMI_MSG_RESET_DOMAIN 1
#define CFG_SCMI_MSG_SHM_MSG 1
#define CFG_SCMI_MSG_SMT 1
/* CFG_SCMI_MSG_SMT_FASTCALL_ENTRY is not set */
/* CFG_SCMI_MSG_SMT_INTERRUPT_ENTRY is not set */
#define CFG_SCMI_MSG_SMT_THREAD_ENTRY 1
/* CFG_SCMI_MSG_THREAD_ENTRY is not set */
/* CFG_SCMI_MSG_USE_CLK is not set */
#define CFG_SCMI_MSG_VOLTAGE_DOMAIN 1
#define CFG_SCMI_PTA 1
/* CFG_SCMI_SCPFW is not set */
/* CFG_SCMI_SCPFW_FROM_DT is not set */
/* CFG_SCTLR_ALIGNMENT_CHECK is not set */
#define CFG_SECONDARY_INIT_CNTFRQ 1
#define CFG_SECSTOR_TA 1
#define CFG_SECSTOR_TA_MGMT_PTA 1
/* CFG_SECURE_DATA_PATH is not set */
/* CFG_SECURE_PARTITION is not set */
#define CFG_SECURE_TIME_SOURCE_CNTPCT 1
/* CFG_SEMIHOSTING is not set */
/* CFG_SEMIHOSTING_CONSOLE is not set */
#define CFG_SEMIHOSTING_CONSOLE_FILE "optee.log"
/* CFG_SHOW_CONF_ON_BOOT is not set */
#define CFG_SM_NO_CYCLE_COUNTING 1
#define CFG_SM_PLATFORM_HANDLER 1
/* CFG_SPMC_TESTS is not set */
#define CFG_SP_INIT_INFO_MAX_SIZE 0x1000
#define CFG_STACK_THREAD_EXTRA 0
#define CFG_STACK_TMP_EXTRA 0
/* CFG_STM32MP13 is not set */
#define CFG_STM32MP15 1
#define CFG_STM32MP15_CLK 1
/* CFG_STM32MP15_HUK is not set */
#define CFG_STM32MP1_RSTCTRL 1
#define CFG_STM32MP1_SCMI_SHM_BASE 0
#define CFG_STM32MP1_SCMI_SHM_SIZE 0x1000
/* CFG_STM32MP1_SCMI_SHM_SYSRAM is not set */
/* CFG_STM32MP1_SCMI_SIP is not set */
#define CFG_STM32MP_PANIC_ON_TZC_PERM_VIOLATION 1
/* CFG_STM32MP_REMOTEPROC is not set */
#define CFG_STM32_ALLOW_UNSAFE_PROBE 1
#define CFG_STM32_BSEC 1
#define CFG_STM32_BSEC_PTA 1
#define CFG_STM32_BSEC_SIP 1
#define CFG_STM32_BSEC_WRITE 1
/* CFG_STM32_CPU_OPP is not set */
/* CFG_STM32_CRYP is not set */
#define CFG_STM32_CRYPTO_DRIVER 1
/* CFG_STM32_DEBUG_ACCESS is not set */
#define CFG_STM32_DEBUG_ACCESS_PTA 1
#define CFG_STM32_EARLY_CONSOLE_UART 4
#define CFG_STM32_ETZPC 1
#define CFG_STM32_EXTI 1
#define CFG_STM32_GPIO 1
#define CFG_STM32_HASH 1
/* CFG_STM32_HUK_FROM_DT is not set */
#define CFG_STM32_I2C 1
#define CFG_STM32_IWDG 1
/* CFG_STM32_PKA is not set */
#define CFG_STM32_RNG 1
#define CFG_STM32_RSTCTRL 1
#define CFG_STM32_RTC 1
/* CFG_STM32_RTC_HIGH_ACCURACY is not set */
/* CFG_STM32_SAES is not set */
#define CFG_STM32_SAES_SW_FALLBACK 1
#define CFG_STM32_SHARED_IO 1
#define CFG_STM32_TAMP 1
#define CFG_STM32_UART 1
#define CFG_STPMIC1 1
/* CFG_SYSCALL_FTRACE is not set */
/* CFG_SYSCALL_WRAPPERS_MCOUNT is not set */
#define CFG_SYSTEM_PTA 1
#define CFG_TA_ASLR 1
#define CFG_TA_ASLR_MAX_OFFSET_PAGES 128
#define CFG_TA_ASLR_MIN_OFFSET_PAGES 0
/* CFG_TA_BGET_TEST is not set */
#define CFG_TA_BIGNUM_MAX_BITS 2048
/* CFG_TA_BTI is not set */
#define CFG_TA_FLOAT_SUPPORT 1
/* CFG_TA_GPROF_SUPPORT is not set */
#define CFG_TA_LIBGCC 1
#define CFG_TA_MBEDTLS 1
#define CFG_TA_MBEDTLS_MPI 1
#define CFG_TA_MBEDTLS_SELF_TEST 1
/* CFG_TA_MBEDTLS_UNSAFE_MODEXP is not set */
/* CFG_TA_OPTEE_CORE_API_COMPAT_1_1 is not set */
/* CFG_TA_PAUTH is not set */
/* CFG_TA_SANITIZE_UNDEFINED is not set */
/* CFG_TA_STACK_PROTECTOR is not set */
/* CFG_TA_STACK_PROTECTOR_ALL is not set */
#define CFG_TA_STACK_PROTECTOR_STRONG 1
/* CFG_TA_STATS is not set */
#define CFG_TA_STRICT_ANNOTATION_CHECKS 1
#define CFG_TEE_API_VERSION GPD-1.1-dev
/* CFG_TEE_CORE_DEBUG is not set */
#define CFG_TEE_CORE_EMBED_INTERNAL_TESTS 1
#define CFG_TEE_CORE_LOG_LEVEL 2
/* CFG_TEE_CORE_MALLOC_DEBUG is not set */
#define CFG_TEE_CORE_NB_CORE 2
#define CFG_TEE_CORE_TA_TRACE 1
#define CFG_TEE_DYN_VASPACE_SIZE (1024 * 1024)
#define CFG_TEE_FW_IMPL_VERSION FW_IMPL_UNDEF
#define CFG_TEE_FW_MANUFACTURER FW_MAN_UNDEF
#define CFG_TEE_IMPL_DESCR OPTEE
#define CFG_TEE_MANUFACTURER LINARO
#define CFG_TEE_RAM_VA_SIZE 0x00200000
#define CFG_TEE_TA_LOG_LEVEL 1
/* CFG_TEE_TA_MALLOC_DEBUG is not set */
/* CFG_TRANSFER_LIST is not set */
/* CFG_TRANSFER_LIST_TEST is not set */
#define CFG_TZC400 1
#define CFG_TZDRAM_SIZE 0x02000000
#define CFG_TZDRAM_START 0xfe000000
#define CFG_TZSRAM_SIZE 0x00040000
#define CFG_TZSRAM_START 0x2ffc0000
/* CFG_ULIBS_MCOUNT is not set */
/* CFG_ULIBS_SHARED is not set */
/* CFG_UNWIND is not set */
/* CFG_VERAISON_ATTESTATION_PTA is not set */
#define CFG_VERAISON_ATTESTATION_PTA_TEST_KEY 1
#define CFG_WARN_DECL_AFTER_STATEMENT 1
#define CFG_WDT 1
#define CFG_WDT_SM_HANDLER 1
#define CFG_WDT_SM_HANDLER_ID 0xbc000000
/* CFG_WIDEVINE_HUK is not set */
/* CFG_WIDEVINE_PTA is not set */
/* CFG_WITH_LPAE is not set */
#define CFG_WITH_NSEC_GPIOS 1
#define CFG_WITH_NSEC_UARTS 1
#define CFG_WITH_PAGER 1
#define CFG_WITH_SOFTWARE_PRNG 1
#define CFG_WITH_STACK_CANARIES 1
#define CFG_WITH_STATS 1
/* CFG_WITH_STMM_SP is not set */
#define CFG_WITH_USER_TA 1
#define CFG_WITH_VFP 1
#define PLATFORM_FLAVOR 157A_DHCOR_AVENGER96
#define PLATFORM_FLAVOR_157A_DHCOR_AVENGER96 1
#define PLATFORM_stm32mp1 1
/* _CFG_ARM_V3_OR_V4 is not set */
/* _CFG_CORE_ASYNC_NOTIF_DEFAULT_IMPL is not set */
#define _CFG_CORE_LTC_ACIPHER 1
#define _CFG_CORE_LTC_AES 1
/* _CFG_CORE_LTC_AES_ACCEL is not set */
#define _CFG_CORE_LTC_AES_DESC 1
#define _CFG_CORE_LTC_ASN1 1
#define _CFG_CORE_LTC_BIGNUM_MAX_BITS 4096
#define _CFG_CORE_LTC_CBC 1
#define _CFG_CORE_LTC_CBC_MAC 1
#define _CFG_CORE_LTC_CCM 1
/* _CFG_CORE_LTC_CE is not set */
#define _CFG_CORE_LTC_CMAC 1
#define _CFG_CORE_LTC_CTR 1
#define _CFG_CORE_LTC_CTS 1
#define _CFG_CORE_LTC_DES 1
#define _CFG_CORE_LTC_DH 1
#define _CFG_CORE_LTC_DSA 1
#define _CFG_CORE_LTC_EC25519 1
#define _CFG_CORE_LTC_ECB 1
#define _CFG_CORE_LTC_ECC 1
#define _CFG_CORE_LTC_ED25519 1
#define _CFG_CORE_LTC_HASH 1
#define _CFG_CORE_LTC_HMAC 1
/* _CFG_CORE_LTC_HWSUPP_PMULL is not set */
#define _CFG_CORE_LTC_MD5 1
#define _CFG_CORE_LTC_MD5_DESC 1
#define _CFG_CORE_LTC_MPI 1
#define _CFG_CORE_LTC_OPTEE_THREAD 1
#define _CFG_CORE_LTC_PAGER 1
#define _CFG_CORE_LTC_RSA 1
#define _CFG_CORE_LTC_SHA1 1
/* _CFG_CORE_LTC_SHA1_ACCEL is not set */
#define _CFG_CORE_LTC_SHA1_DESC 1
#define _CFG_CORE_LTC_SHA224 1
#define _CFG_CORE_LTC_SHA224_DESC 1
#define _CFG_CORE_LTC_SHA256 1
/* _CFG_CORE_LTC_SHA256_ACCEL is not set */
#define _CFG_CORE_LTC_SHA256_DESC 1
#define _CFG_CORE_LTC_SHA384 1
#define _CFG_CORE_LTC_SHA384_DESC 1
#define _CFG_CORE_LTC_SHA3_224 1
#define _CFG_CORE_LTC_SHA3_256 1
#define _CFG_CORE_LTC_SHA3_384 1
#define _CFG_CORE_LTC_SHA3_512 1
/* _CFG_CORE_LTC_SHA3_ACCEL is not set */
#define _CFG_CORE_LTC_SHA3_DESC 1
#define _CFG_CORE_LTC_SHA512 1
#define _CFG_CORE_LTC_SHA512_256 1
/* _CFG_CORE_LTC_SHA512_ACCEL is not set */
#define _CFG_CORE_LTC_SHA512_DESC 1
#define _CFG_CORE_LTC_SHAKE128 1
#define _CFG_CORE_LTC_SHAKE256 1
#define _CFG_CORE_LTC_SIZE_OPTIMIZATION 1
#define _CFG_CORE_LTC_SM2_DSA 1
#define _CFG_CORE_LTC_SM2_KEP 1
#define _CFG_CORE_LTC_SM2_PKE 1
#define _CFG_CORE_LTC_VFP 1
#define _CFG_CORE_LTC_X25519 1
#define _CFG_CORE_LTC_XTS 1
#define _CFG_CORE_STACK_PROTECTOR 1
#define _CFG_SCMI_PTA_MSG_HEADER 1
#define _CFG_SCMI_PTA_SMT_HEADER 1
#define _CFG_TA_STACK_PROTECTOR 1
/* _CFG_USE_DTB_OVERLAY is not set */
#define _CFG_WITH_SECURE_STORAGE 1
#endif
