#!/usr/bin/env perl

use strict;
use warnings;

if ($#ARGV != 0) {
	die "Usage: fixdep <prefix>";
}

my $first_line = 1;

while (<STDIN>) {
	if ($first_line) {
		print "$ARGV[0]$_";
		$first_line = 0;
	} else {
		print "$_";
	}
}
