$(call force,CFG_TEE_CORE_NB_CORE,5)
$(call force,CFG_CORE_CLUSTER_SHIFT,3)
CFG_NUM_THREADS ?= 5

$(call force,CFG_ARM_GICV3,y)

CFG_QCOM_DIAG_LOG ?= $(if $(filter y,$(CFG_TEE_CORE_DEBUG)),y,n)

CFG_TZDRAM_START ?= 0x8A680000
CFG_TZDRAM_SIZE ?= 0x280000
CFG_TEE_RAM_VA_SIZE ?= 0x280000
