/* SPDX-License-Identifier: BSD-2-Clause */
/*
 * Copyright 2017-2018 NXP
 *
 */

#ifndef __IMX6_SRC_REGS_H__
#define __IMX6_SRC_REGS_H__

#define SRC_REGISTER_OFFSET_MASK	0x00FF

#define SRC_SCR				0x0000
#define SRC_SBMR1			0x0004
#define SRC_SRSR			0x0008
#define SRC_SISR			0x0014
#define SRC_SBMR2			0x001C
#define SRC_GPR1			0x0020
#define SRC_GPR2			0x0024
#define SRC_GPR3			0x0028
#define SRC_GPR4			0x002C
#define SRC_GPR5			0x0030
#define SRC_GPR6			0x0034
#define SRC_GPR7			0x0038
#define SRC_GPR8			0x003C
#define SRC_GPR9			0x0040
#define SRC_GPR10			0x0044

#define BP_SRC_SCR_WARM_RESET_ENABLE		0
#define BM_SRC_SCR_WARM_RESET_ENABLE		\
			(1 << BP_SRC_SCR_WARM_RESET_ENABLE)
#define BP_SRC_SCR_SW_GPU_RST			1
#define BP_SRC_SCR_SW_VPU_RST			2
#define BP_SRC_SCR_SW_IPU1_RST			3
#define BP_SRC_SCR_SW_OPEN_VG_RST		4
#define BM_SRC_SCR_SW_OPEN_VG_RST		\
			(1 << BP_SRC_SCR_SW_OPEN_VG_RST)
#define BP_SRC_SCR_WARM_RST_BYPASS_COUNT	5
#define BM_SRC_SCR_WARM_RST_BYPASS_COUNT	\
			(0x3 << BP_SRC_SCR_WARM_RST_BYPASS_COUNT)
#define BP_SRC_SCR_MASK_WDOG_RST		7
#define BM_SRC_SCR_MASK_WDOG_RST		\
			(0xF << BP_SRC_SCR_MASK_WDOG_RST)
#define BP_SRC_SCR_EIM_RST		11
#define BP_SRC_SCR_SW_IPU2_RST		12
#define BP_SRC_SCR_CORE0_RST		13
#define BM_SRC_SCR_CORE0_RST		(1 << BP_SRC_SCR_CORE0_RST)
#define BP_SRC_SCR_CORE1_RST		14
#define BM_SRC_SCR_CORE1_RST		(1 << BP_SRC_SCR_CORE1_RST)
#define BP_SRC_SCR_CORE2_RST		15
#define BM_SRC_SCR_CORE2_RST		(1 << BP_SRC_SCR_CORE2_RST)
#define BP_SRC_SCR_CORE3_RST		16
#define BM_SRC_SCR_CORE3_RST		(1 << BP_SRC_SCR_CORE3_RST)
#define BP_SRC_SCR_CORE0_DBG_RST	17
#define BM_SRC_SCR_CORE0_DBG_RST	(1 << BP_SRC_SCR_CORE0_DBG_RST)
#define BP_SRC_SCR_CORE1_DBG_RST	18
#define BM_SRC_SCR_CORE1_DBG_RST	(1 << BP_SRC_SCR_CORE1_DBG_RST)
#define BP_SRC_SCR_CORE2_DBG_RST	19
#define BM_SRC_SCR_CORE2_DBG_RST	(1 << BP_SRC_SCR_CORE2_DBG_RST)
#define BP_SRC_SCR_CORE3_DBG_RST	20
#define BM_SRC_SCR_CORE3_DBG_RST	(1 << BP_SRC_SCR_CORE3_DBG_RST)
#define BP_SRC_SCR_CORES_DBG_RST	21
#define BP_SRC_SCR_CORE1_ENABLE		22
#define BM_SRC_SCR_CORE1_ENABLE		(1 << BP_SRC_SCR_CORE1_ENABLE)
#define BP_SRC_SCR_CORE2_ENABLE		23
#define BM_SRC_SCR_CORE2_ENABLE		(1 << BP_SRC_SCR_CORE2_ENABLE)
#define BP_SRC_SCR_CORE3_ENABLE		24
#define BM_SRC_SCR_CORE3_ENABLE		(1 << BP_SRC_SCR_CORE3_ENABLE)
#define BM_SRC_SCR_CPU_ENABLE_ALL	(BM_SRC_SCR_CORE1_ENABLE |\
						BM_SRC_SCR_CORE2_ENABLE |\
						BM_SRC_SCR_CORE3_ENABLE)
#define BP_SRC_SCR_DBG_RST_MSK_PG	25
#define BM_SRC_SCR_DBG_RST_MSK_PG	(1 << BP_SRC_SCR_DBG_RST_MSK_PG)


#define SRC_SCR_PROTECTED_MASK	(BM_SRC_SCR_WARM_RESET_ENABLE		|\
					BM_SRC_SCR_WARM_RST_BYPASS_COUNT|\
					BM_SRC_SCR_MASK_WDOG_RST	|\
					BM_SRC_SCR_CORE0_RST		|\
					BM_SRC_SCR_CORE1_RST		|\
					BM_SRC_SCR_CORE2_RST		|\
					BM_SRC_SCR_CORE3_RST		|\
					BM_SRC_SCR_CORE0_DBG_RST	|\
					BM_SRC_SCR_CORE1_DBG_RST	|\
					BM_SRC_SCR_CORE2_DBG_RST	|\
					BM_SRC_SCR_CORE3_DBG_RST	|\
					BM_SRC_SCR_DBG_RST_MSK_PG)

#endif /* __IMX6_SRC_REGS_H__ */
