/* SPDX-License-Identifier: BSD-2-Clause */
/*
 * Copyright (C) 2021 Foundries.io Ltd
 */

#ifndef __DRIVERS_ZYNQMP_EFUSE_H__
#define __DRIVERS_ZYNQMP_EFUSE_H__

#define ZYNQMP_EFUSE_DNA_OFFSET 0xc
#define ZYNQMP_EFUSE_DNA_LENGTH 12

#define ZYNQMP_EFUSE_IP_DISABLE_OFFSET 0x18
#define ZYNQMP_EFUSE_IP_DISABLE_LENGTH 4

#define ZYNQMP_EFUSE_MISC_USER_CTRL_OFFSET 0x40
#define ZYNQMP_EFUSE_MISC_USER_CTRL_LENGTH 4

#define ZYNQMP_EFUSE_SEC_CTRL_OFFSET 0x58
#define ZYNQMP_EFUSE_SEC_CTRL_LENGTH 4

#endif /*__DRIVERS_ZYNQMP_EFUSE_H__*/
